### ISSUE TITLE
APRSdroid not telling mobilinkd TNC2 to transmit

### ISSUE THREAD

**Issue by chandwer** [ge0rg/aprsdroid#100]
The log shows that aprsdroid is able to connect to the TNC. Using the mobilinkd configuration app I am able to verify that it can TX/RX to and from my radio.

The problem is that when I hit the single shot button or let it sit for a while no packets are transmitted. It also appears that no packets are received.

I am using a Samsung Galaxy S4 with CyanogenMod 11 which is android version 4.4.4.

Any ideas?

![screenshot_2015-03-16-11-58-41](https://cloud.githubusercontent.com/assets/4529260/6670315/4a6edfd6-cbd4-11e4-95ee-191e6dd8fedd.png)

**Comment by ge0rg** [comment]
APRSdroid should send a position as soon as you get a GPS fix - maybe you can try the "GPS Status" app to see if you get sufficient satellites in view to let APRSdroid generate a position packet.

From what your TNC2 outputs, everything looks good. Maybe there is an issue with the audio volume or some other effect preventing the TNC2 from decoding packets?

**Comment by chandwer** [comment]
Ah, when I was testing the device I was in a building with a metal roof and probably didn't have a GPS fix.

When I tested later in my car it did work.
