### ISSUE TITLE
ProGuard EmptyStackException when building.

### ISSUE THREAD

**Issue by dandrzejewski** [ge0rg/aprsdroid#102]
I'm not entirely sure if this is something wrong with my setup or not, but I haven't been able to find much on Google.

When I run ant to build APRSDroid, with ProGuard 5.2, I get an EmptyStackException. I've copied the entire "ant debug" output.

https://gist.github.com/dandrzejewski/718194496eea010933f5

Any help would be appreciated, I'm hoping to contribute!

**Comment by wfrisby** [comment]
I don't know if this helps but I was able to build successfully with ProGuard 5.2.1 from http://sourceforge.net/projects/proguard/ . Maybe give it a try? For what its worth, I'm also using Oracle's JDK v1.7 on Ubuntu 14.04 with Android SDK Tools Revision 24.1.2.

**Comment by ge0rg** [comment]
I'm using ancient proguard 4.8 beta1. Not sure if this is a proguard bug or related to APRSdroid.

**Comment by ge0rg** [comment]
I've updated build.xml to use Android's default ProGuard.jar, which is version 4.7 and works as well. Maybe you can try the latest master branch?
