### ISSUE TITLE
2 issues- 1- SINGLE SHOT delay and 2- many steps to re-que a message

### ISSUE THREAD

**Issue by omaudio** [ge0rg/aprsdroid#104]
Hi, thanks for the app. Bought the market ver to help.
My goal is to use the app to produce APRS audio with a message to get a message to an APRS gateway. (I so ham radio for SOTA and will use APRS to "spot" myself from mountain tops)
1- one shots often occur at random intervals after I press SINGLE SHOT
2- to re-send the message I have created which will reach the APRS2SOTA gateway takes 7 steps. ideally I could re-que it much quicker.

Describe the Situation

Issue 1- 
    What did you want to accomplish?
send multiple single shots from speaker to mic on radio
    What were the exact steps you performed?
set location, message, audio out- press single shot
    What was the expected outcome?
immediate APRS as audio from speaker
    What happened instead?
random lengths of time pass before audio is heard if at all
    What APRSdroid configuration were you using (SmartBeaconing/Periodic/..., TCP/Bluetooth/AFSK/...)?
audio out

Issue 2- 
Describe the Situation

    What did you want to accomplish?
send a message multiple times to reach a gateway
    What were the exact steps you performed?
create message, send as single shot
    What was the expected outcome?
ability to easily send the message again
    What happened instead?
7 steps required to re-send the message
    What APRSdroid configuration were you using (SmartBeaconing/Periodic/..., TCP/Bluetooth/AFSK/...)?
audio out

**Comment by ge0rg** [comment]
## Issue 1: Single Shot Delay

In "Single Shot" mode, APRSdroid first needs to acquire a GPS fix before it can send its location out. This takes some seconds up to a minute, depending on the GPS signal quality.

I recommend changing into Manual Position mode and storing the coordinates in APRSdroid, and using the "Start Tracking" functionality. Then you can trigger a position TX by simply pressing "Single Shot" whenever you need the data to be sent out.

For "Manual Position" you can disable automatic transmissions, so the radio will only be keyed when you explicitly push "Single Shot".

## Issue 2: Re-Sending of Messages

Again, I would recommend using the "Start Tracking" mode. In that mode, all you need to do to re-send a message is to long-tap the message and select "Resend".

**Comment by omaudio** [comment]
this simply does not work.
I already have it set to manual location with "automatic posting" turned off
when you set "start tracking" it plays the audio and does not play when you hit single shot.

**Comment by ge0rg** [comment]
This is really strange. Can you please [provide a logcat from the device](https://github.com/ge0rg/aprsdroid/wiki/Reporting-Bugs#provide-a-logcat)? I hope to be able to obtain additional data from it.

Thanks.

**Comment by omaudio** [comment]
Hi,
So I did get the single shot to work but the issue remains that there is no way to know when a message is being transmitted and no way to re-transmit a message in less than 7 steps or so. If there were a way to send a message as a single shot as many times as desired with good visual feedback that would be ideal.
Thanks
C
