### ISSUE TITLE
aprsdroid Improvement

### ISSUE THREAD

**Issue by unzihe** [ge0rg/aprsdroid#106]
APRSdroid increase proposal to start automatically and start the program automatically open trail

Increase the watchdog, abnormal program termination, automatic restart

Really looking forward to this new feature

**Comment by ge0rg** [comment]
If you wish to start APRSdroid tracking automatically, I would suggest using a third-party app like Tasker. There is a [FAQ entry](https://github.com/ge0rg/aprsdroid/wiki/Frequently-Asked-Questions#how-do-i-automate-aprsdroid-with-eg-tasker) for the according configuration.

APRSdroid is automatically restarted by the OS if it gets killed, and it automatically reconnects to APRS whenever something bad happens.
