### ISSUE TITLE
Update build instructions (PacketDroid)

### ISSUE THREAD

**Issue by dack** [ge0rg/aprsdroid#107]
I'm interested in contributing to this project, but I can't seem to get it to build. It seems that some files need to be copied over from PacketDroid? I've followed the instructions [on the wiki](https://github.com/ge0rg/aprsdroid/wiki/Developer), but it doesn't include any of the PacketDroid stuff. Any chance we can get some updated build instructions to help potential contributors? Thanks!

**Comment by ge0rg** [comment]
Hi! It's awesome to see some interest in contributing. I'm sorry the build instructions are so badly out of date; Adding PacketDroid was a quick hack and I never resolved to a proper solution.

I have updated the build instructions to document the state of affairs. I can't claim that I am proud of it, but it should at least get you going.

Georg

**Comment by dack** [comment]
Thanks! I'll give it a go as soon as I have some time.

**Comment by dack** [comment]
Which JDK are you using? It seems like scala 2.8.2 does not like JDK 1.8.0_20. I tried scala 2.11.7, but it gives syntax errors on some of the aprsdroid code.

**Comment by ge0rg** [comment]
I'm building all my Android apps with 1.7.0_79 - I heard 1.8 isn't there
yet for building Android apps, but maybe I'm lagging here as well ;)

**Comment by dack** [comment]
JDK 1.7 works, but now it's failing on proguard. Which proguard version do you use?

**Comment by ge0rg** [comment]
I'm using proguard 4.8b1, which is a bit out of date as well :>
