### ISSUE TITLE
Feature Request: Navigate to point on map

### ISSUE THREAD

**Issue by dandrzejewski** [ge0rg/aprsdroid#108]
It would be great to be able to tap on a station or point on the map and have it switch over to Google Maps or some other navigation program to provide turn-by-turn directions.

**Comment by ge0rg** [comment]
As of c87deb936daa45b13a76379f2fdda218d77ada76 you can open a station in an external map from the options and context menus.

APK: http://aprsdroid.org/download/builds/APRSdroid-gl-2016-10-06.apk
