### ISSUE TITLE
Feature request: switchable profiles

### ISSUE THREAD

**Issue by sh123** [ge0rg/aprsdroid#111]
It would be nice if Aprsdroid will support profiles and quick switching between them. For example, I can define two profiles, one for car and one for bicycle with different SSIDs, icons. Profile could also support specifying different APRS sending logic and/or connection type, etc.

**Comment by ge0rg** [comment]
Yeah, this is an important feature to have, but I am still not quite sure how to best address it, internally and for the UI. Please follow the progress in #68, thanks.
