### ISSUE TITLE
Feature Request: change APRS Symbol field to picker with sample images

### ISSUE THREAD

**Issue by W7PEA** [ge0rg/aprsdroid#118]
The current way APRS symbols are set is by knowing them by heart or looking them up. That's not always possible when you are out of cell coverage. It would be better if the APRS Symbol was a picker of all the icons or a drop down with icons and explanatory text.. many ways to go.

Here are some resources you can use to implement this: 

* [APRS icons in vector format](https://github.com/hessu/aprs-symbols)
* [This is a machine-readable index of APRS symbol descriptions.](https://github.com/hessu/aprs-symbol-index)

**Comment by Padgett** [comment]
:+1: I would love to see this as well

**Comment by ge0rg** [comment]
Now this has been pending for faaaaar to long.
New apk: http://aprsdroid.org/download/builds/APRSdroid-gl-2016-09-21.apk

Result:
![aprsdroid-symbol](https://cloud.githubusercontent.com/assets/165635/18703654/21079fe8-7fe7-11e6-9272-8f24e73d0b90.png)

Please test and report back!
