### ISSUE TITLE
Suppress via-Field "TCPIP*" in APRS packets generated for IP transmission

### ISSUE THREAD

**Issue by dh3wr** [ge0rg/aprsdroid#119]
Hi Georg,
Today I tried to get running a setup, where I use my smartphone with your very good App connected via Wifi to a on-Car Accesspoint and an on-Car Raspi. The Raspberry is running aprx with a TNC2 and a 2m radio and is connected to a aprs server aprsc, running on the same Raspberry. So I can do APRS with my phone without any need to connecting vias, the combination of aprx, wifi, ap and aprsc builds up a mobile aprs Digipeater in my car. Now: Packets generated from aprsdroid contain "TCPIP*" in the via-fields. Although they are perfectly reflected by my mobile aprsc instance and sent out by the radio via aprx, the aprs-igate-conventions say, that any packet with TCPIP(*) in is is not going to the APRSIS upstream. So, when I drive around, other APRS-Digis repeat my packet, but don't send it to the APRSIS network.

Do you see any chance of making a possibiliy to disable in special cases the "TCPIP*" in the generated packets of your App? Thank you very much in advance!
Ralf DH3WR

**Comment by ge0rg** [comment]
This is exactly what the "TCP/IP TNC" setting is for.
