### ISSUE TITLE
Feature Request: Integration with Kenwood THD72A 

### ISSUE THREAD

**Issue by mrearp** [ge0rg/aprsdroid#12]
It would be nice to be able to plug my tablet into my Kenwood and be able to do APRS.. 

Would also be nice to download maps as well..

**Comment by ge0rg** [comment]
I have uploaded an [alpha version with USB support](http://aprsdroid.org/download/builds/APRSdroid-gl-2015-08-27_usb2.apk). Please test if you can connect it to the D72 in "PACKET" mode; APRSdroid is expecting KISS packets over USB.

**Comment by N7KFD** [comment]
I'm a little late to the party but here are a couple of screen shots. The first one is with the TNC on the TH-D72 in packet mode.

![screenshot_20160319-182608](https://cloud.githubusercontent.com/assets/17956315/13902131/d73f5f4e-ee01-11e5-96a8-f516599eaee5.png)

The second is with the TNC in APRS mode and the GPS turned on.

![screenshot_20160319-182736](https://cloud.githubusercontent.com/assets/17956315/13902134/eef2d0bc-ee01-11e5-9b51-9344489ddb54.png)

**Comment by ge0rg** [comment]
@N7KFD the packet mode is theoretically the way to go. Can you provide a screenshot right after receiving some APRS packets? Do they show up at all?

**Comment by ge0rg** [comment]
New APK that supports both KISS and Kenwood modes, over both Bluetooth SPP and USB: http://aprsdroid.org/download/builds/APRSdroid-gl-2016-09-21.apk

Please test!

**Comment by ge0rg** [comment]
Good news! Our local club has its field day today, and we've managed to get APRSdroid to work with TH-D72 in both modes:

* Kenwood waypoint mode via 2.5mm plug (GPS / waypoint as described in https://aprsdroid.org/kenwood/), using a Bluetooth SPP adapter for the Kenwood port.
* KISS mode via USB serial with the latest APK build, with following TNC init string:

    KISS ON
    RESTART

It looks like the D72 doesn't support waypoint mode over the USB port, nor KISS over GPS port.


![aprsdroid-d72-kiss](https://cloud.githubusercontent.com/assets/165635/18809232/b6c2cc2e-8276-11e6-83b9-16e3a1a4e36f.jpg)

**Comment by cx5cba** [comment]
I Have the V1.4.0 RC3 and don´t do that my TH-D72 Works through USB. 
What is the right settings in the HT and the APRSDroid?

**Comment by ge0rg** [comment]
@cx5cba Settings to use the combo:
* D72: KISS mode (might also be called PACKET in the UI)
* APRSdroid: "TNC (KISS)" mode with "USB serial"
* Check that both devices are configured to the same baud rate, though in theory it should autodetect
* Connect them via USB cable, there should be a popup on the Android, asking to give APRSdroid the permissions for USB (or a list with APRSdroid and other installed apps)
