### ISSUE TITLE
TNC Init String enter ESC@K to get KISS Mode

### ISSUE THREAD

**Issue by dh3wr** [ge0rg/aprsdroid#121]
Hi,
I have a Symek TNC2S connected via Bluetooth-Serial Adapter. Unfortunately, I need to send the sequence "ESC@K" to the TNC to bring it in KISS mode. How do I enter the ESC ASCII Character in the TNC Init String field? In Hex this would be 0x1B. I got it running with a separate BT-Terminal Program, but everytime the TNC is powered on, I have to execute the extra app to get the TNC ready in KISS mode.

Best regards
Ralf DH3WR

**Comment by dg1tal** [comment]
I ran into this issue a year ago and stuck to the same workarround you chose. ;-)

Did you since find a way to enter the ASCII escape char in aprsdroid?

**Comment by dh3wr** [comment]
Hi, unfortunately no advance in this issue. I looked at the sources and found the place to enter the 0x1B, but was not able to compile it. I'm not an android programming expert. If someone has set up a working toolchain to compile the sources, I would be happy to provide a patched version. Let me know.

**Comment by ge0rg** [comment]
This is essentially about choosing an encoding for special characters that can be proceeded by Scala / java code with little effort. I just realized that URL encoding, while not the most elegant, is readily available and easy to add. Would that be okay for your use case?

**Comment by dg1tal** [comment]
I'm pretty sure that would work. \o/

**Comment by ge0rg** [comment]
Okay, [build with URL-encoded TNC init parameter](http://aprsdroid.org/download/builds/APRSdroid-gl-2016-05-18.apk). Please test and report back.

**Comment by km4kqq** [comment]
> dh3wr: What BT-Terminal client do you use?  I can not connect to my Android using the one I have.  It is paired with my TinyTrak Bluetooth unit.

> Dh3wr: Was BT-Terminal-Client verwenden Sie? Ich kann nicht auf mein Android verbinden Sie das eine mit den ich habe. Es ist mit meinem TinyTrak Bluetooth-Gerät gepaart.

**Comment by stephensworld** [comment]
This worked for me with a TNC2 TF2.7
%0D%1B T 12
%0D%1B @K

T 12 is for tx delay


Thanks

Best regards
Stephan
