### ISSUE TITLE
Feature Request: Kenwood GPS Mode with USB Serial

### ISSUE THREAD

**Issue by stephensworld** [ge0rg/aprsdroid#122]
Hi,

is it possible to add a feature to use the Kenwood GPS Port with USB Serial?

Thank you very much.

73
Stephan

**Comment by ge0rg** [comment]
This is possible and planned indeed. I need to do some refactoring which will allow different combinations of protocol (KISS/TNC2/...) and connection (USB Serial/Bluetooth/TCP/...)

**Comment by ge0rg** [comment]
Please test this APK: http://aprsdroid.org/download/builds/APRSdroid-gl-2016-09-21.apk

**Comment by ge0rg** [comment]
This is part of the current 1.4 beta and will be released soon.
