### ISSUE TITLE
Feature Request: PTT with USB serial

### ISSUE THREAD

**Issue by stephensworld** [ge0rg/aprsdroid#123]
Hi,

in order to use a general TRX with AFSK and 5pin Packet data connector it would be great to set PTT with USB serial Interface. e.g. CTS or DSR
So the delay would be very short in comparison to VOX.

Thank you

73
Stephan

**Comment by ge0rg** [comment]
This would be hard to pull off with APRSdroid's current architecture; it would need two different USB-serial modes (one for AFSK-PTT and the other one for USB TNCs). I will be pondering about this for a while, but in the meantime it might be easier and more robust to make an Arduino-based TNC that offloads the AFSK parts.

**Comment by ge0rg** [comment]
While I can see a use case for this, there are several reasons why I'm not investing much time into AFSK support any more:

* the phone's audio connection is not very reliable, and it can catch your RF emissions and damage your phone
* Android might make notification sounds which would be emitted to RF
* AFSK decoding keeps the CPU awake, using up battery.

On the other hand, you can attach a USB-serial TNC (like the TH-D72) or something like the [Mobilinkd TNC](http://www.mobilinkd.com/tnc2/), which is a Bluetooth-connected battery-powered TNC with PTT support, so there are many alternative options.
