### ISSUE TITLE
Minus Sign in Longitude

### ISSUE THREAD

**Issue by ChuckBland** [ge0rg/aprsdroid#125]
Pressing on and playing.....

I haven't found where to tap for the minus sign when entering Longitude.

If I use the "Use Last Coords" function, it puts it in, but I don't seem to be able to do so manually.

What have I missed?

Chuck

**Comment by ge0rg** [comment]
On some devices (I know of at least Amazon Fire) the system keyboard is buggy and does not allow entry of negative numbers. You can copy&paste the minus sign from another app, though.

You can also install an alternative keyboard app, like the Google Keyboard or SwiftKey.

**Comment by ChuckBland** [comment]
......why didn't I think of that......

I just installed the Google Keyboard. Problem solved.
