### ISSUE TITLE
Tracking starts and immediately shuts down.

### ISSUE THREAD

**Issue by JohnE23** [ge0rg/aprsdroid#126]
After pairing with my Galaxy Tab 2/7 running 4.2 or my S6 running 5.1, my TNC2 Bluetooth TNC connects but when I initiate tracking I get the following:

APRS Service Started: Periodic GPS/Network Position, Bluetooth TNC
Error
java.io.IOException: read failed, socket might closed or timeout, read ret: -1

**Comment by mobilinkd** [comment]
It is almost certain that the Mobilinkd Config app has the Bluetooth connection open when you see this error.  You will need to re-open the Mobilinkd Config app and press "Disconnect" before opening APRSdroid and pressing the "Start Tracking" button.  Only one app can talk to the TNC at a time.

**Comment by JDogHerman** [comment]
I also have this same issue.

I am using an LG Phoenix 2 with a Moblinkd TNC2 over bluetooth. I have unpaired & paired the bluethooth, Removed the moblinkd app and restarted the phone. 

I am getting the same error: java.io.IOException: read failed, socket might closed or timeout, read ret: -1

My android version is 6.0 patch level=2016-07-01 with Kernel=3.10.49

**Comment by JohnE23** [comment]
Make sure to disconnect  the Mobilinkd config app before trying to track. The device can only link to one device at a time.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Justin Herman <notifications@github.com> Date: 12/1/16  11:14  (GMT-07:00) To: ge0rg/aprsdroid <aprsdroid@noreply.github.com> Cc: JohnE23 <jhnccls@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [ge0rg/aprsdroid] Tracking starts and immediately shuts down. (#126) 
I also have this same issue.
I am using an LG Phoenix 2 with a Moblinkd TNC2 over bluetooth. I have unpaired & paired the bluethooth, Removed the moblinkd app and restarted the phone.
I am getting the same error: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
My android version is 6.0 patch level=2016-07-01 with Kernel=3.10.49

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ge0rg/aprsdroid","title":"ge0rg/aprsdroid","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ge0rg/aprsdroid"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JDogHerman in #126: I also have this same issue.\r\n\r\nI am using an LG Phoenix 2 with a Moblinkd TNC2 over bluetooth. I have unpaired \u0026 paired the bluethooth, Removed the moblinkd app and restarted the phone. \r\n\r\nI am getting the same error: java.io.IOException: read failed, socket might closed or timeout, read ret: -1\r\n\r\nMy android version is 6.0 patch level=2016-07-01 with Kernel=3.10.49"}],"action":{"name":"View Issue","url":"https://github.com/ge0rg/aprsdroid/issues/126#issuecomment-264249503"}}}

**Comment by JDogHerman** [comment]
I have made sure it was disconnected. I also uninstalled the app too just to be safe :)

**Comment by JohnE23** [comment]
Install the app and paired the phone. Configure the app. then disconnect. You can the connect to your phone or tablet and it should track normally.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Justin Herman <notifications@github.com> Date: 12/1/16  11:40  (GMT-07:00) To: ge0rg/aprsdroid <aprsdroid@noreply.github.com> Cc: JohnE23 <jhnccls@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [ge0rg/aprsdroid] Tracking starts and immediately shuts down. (#126) 
I have made sure it was disconnected. I also uninstalled the app too just to be safe :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ge0rg/aprsdroid","title":"ge0rg/aprsdroid","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ge0rg/aprsdroid"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JDogHerman in #126: I have made sure it was disconnected. I also uninstalled the app too just to be safe :)"}],"action":{"name":"View Issue","url":"https://github.com/ge0rg/aprsdroid/issues/126#issuecomment-264256076"}}}
