### ISSUE TITLE
Feature Request: More readable tracking lines

### ISSUE THREAD

**Issue by skidoo** [ge0rg/aprsdroid#128]
Thank you for providing this great tool.
On OSM version I can hardly see track lines as mobiles move around.  Expect some folks want to minimize while others want tracking lines more visible.  Would be nice to have options to set line widths and color.  For example lines used on aprs.fi are easy to see.
Best regards,
Cliff

**Comment by ge0rg** [comment]
I've shamelessly stolen the track lines from aprs.fi, please test and have fun:

https://aprsdroid.org/download/builds/APRSdroid-gl-2016-10-06_osm.apk

**Comment by skidoo** [comment]
Thanks for resolving this.
