### ISSUE TITLE
Support for different Maps backends

### ISSUE THREAD

**Issue by gps-au** [ge0rg/aprsdroid#13]
I just had a quick look thru the code here and wonder why use google mapping direct ?

Most if not all Android devices have google maps installed, and may there are others (like myself) who might even have say "Brut" maps and are using the "tile pre-caching" to reduce data costs (& have the data when 3G isn't available).

So why not interface to the already installed maps ?  

Alternatively, be able to use a pre-cache tile store ?

GS

**Comment by Biffvj** [comment]
I use topographic terrain maps of South Africa on Oruxmaps (Android) offline or flight mode,  I would like to use them with APRSDroid. There is no cell phone reception where we operate. Oruxmaps uses an SQLite Map file with an XML Doc. Good resolution 1:50000 topographic map with multiple zoom levels is only 55Kb in size. Google maps really sucks where there is no cell phone signal.

**Comment by ge0rg** [comment]
Maybe you can find a way to export your maps into the OpenStreetMap format, and convert it from there into the mapsforge format? I fear I am not able to add map renderers for all the map types out there.
