### ISSUE TITLE
Feature request: DIGIPEATER

### ISSUE THREAD

**Issue by cx5cba** [ge0rg/aprsdroid#131]
I used APRSDROID for 3 years or more and really like it.
The only feature that I would have is DIGIPEATER.
Recently I saw that there is an APP for iPhone called APRS Pro that has the function of digipeater but I do not want to switch to iPhone and all the features of APRSDROID are really good.

Thanks

Carlos CX5CBA

**Comment by ge0rg** [comment]
Thanks for the feedback. Implementing a digi is challenging, and I have it on my agenda. However, I can not promise a solution any time soon.

**Comment by ge0rg** [comment]
Please subscribe to #89, the original digipeater feature request. I'll close this issue as a duplicate. Thanks.
