### ISSUE TITLE
LoTW client certificate not found by APRSdroid

### ISSUE THREAD

**Issue by bnordgren** [ge0rg/aprsdroid#136]
- What did you want to accomplish?

Install LoTW certificate into APRSDroid for authentication 
- What were the exact steps you performed?

http://aprsdroid.org/ssl
- What was the expected outcome?

Authentication to server
- What happened instead?

"No certificate for AF7RQ! Using passcode authentication". NOTE: Although I requested my passcode sometime last year, have not yet received a response; consistent with many comments/reviews. No authentication possible.
- What APRSdroid configuration were you using (SmartBeaconing/Periodic/..., TCP/Bluetooth/AFSK/...)?

TCP, ssl.aprs2.net, connection logging enabled.

Running on Google Nexus 7 tablet (2012), Android version 5.1.1. Not rooted/no logs.

I ran my *.p12 file transferred to the tablet through openssl and attached the result. Under Settings -> Security -> Trusted Credentials -> User, I see two entries for ARRL (Root CA/Production CA), but I don't see/don't know how to view my client certificate.

[AF7RQ.txt](https://github.com/ge0rg/aprsdroid/files/350272/AF7RQ.txt)

**Comment by ge0rg** [comment]
Your certificate looks alright to me. You need to tap it from the email/file browser app on Android, and select "SSL keyfile import" (with APRSdroid logo). It will then be imported into APRSdroid and used on SSL connections.

I'm sorry to hear that you had no success getting a passcode, but I also can't find a request for AF7RQ in our passcode request tracker or in my mailbox. I hate the APRS-IS passcode situation as much as (or even more than) the people who complain about it in the APRSdroid reviews, but this is how the Demi-Gods of APRS-IS designed it and They Demand a manual passcode approval process (despite there being many APRS-IS passcode generators on the Internet).

**Comment by bnordgren** [comment]
Clicking on it directly from email was the process I followed. I did try again, using a different password. Both times, android reported that 

> The package contains:
> - one user key
> - one user certificate
> - 2 CA certificates

So I assume that it should be able to locate a certificate and the private key for AF7RQ. But somehow it isn't.

**Comment by ge0rg** [comment]
* bnordgren <notifications@github.com> [2016-07-06 18:14]:
> Both times, android reported that [...]

Hm... that really looks like it can't open the file with APRSdroid.
Could you please try the [latest APRSdroid
APK](https://aprsdroid.org/download/builds/APRSdroid-gl-2016-05-18.apk)?

-- 
|| http://op-co.de ++  GCS d--(++) s: a C+++ UL+++ !P L+++ !E W+++ N  ++
|| gpg: 0x962FD2DE ||  o? K- w---() O M V? PS+ PE-- Y++ PGP+ t+ 5 R+  ||
|| Ge0rG: euIRCnet ||  X(+++) tv+ b+(++) DI+++ D- G e++++ h- r++ y?   ||
++ IRCnet OFTC OPN ||_________________________________________________||

**Comment by bnordgren** [comment]
Oh, BTW,

When tapping on the attachment in email, there's no opportunity to select anything (SSL keyfile import with Android logo). It goes straight to "Extract certificate, Type the password to extract the certificates. [Cancel/Ok]" Same thing happens when you click the download icon and then select the file from the notification bar. 

Just saw your update. Will download the latest build. (Was using 1.3.0)

**Comment by bnordgren** [comment]
Same result with the latest build.

**Comment by ge0rg** [comment]
Thank you very much for testing. It looks like the filter I had for the .p12 files was too restrictive, and failed to register for email attachments.

I have uploaded [a new build](http://aprsdroid.org/download/builds/APRSdroid-gl-2016-08-03.apk) which at least works for me with K9-Mail and File Manager. I hope you will be able to import the key with it.

**Comment by ge0rg** [comment]
It looks like the last filter was a little bit too lax and popped up APRSdroid for almost any email attachment and file open dialog. Please test [this new APK](http://aprsdroid.org/download/builds/APRSdroid-gl-2016-09-09.apk) and let me know if it successfully opens your .p12 file. TNX.

**Comment by n3farious** [comment]
I didn't open the issue, but this latest build fixed for me on Nougat with Nexus 6P.  Now I get a response from server that my certificate has expired.

**Comment by derekmurawsky** [comment]
I'm having the same issue. Galaxy S5. 
There is no way for me to bypass the system key importer. 
Is there any way you could implement the functionality within the menu system so we can browse/select the file from within APRSDroid?
Thanks for the app.

**Comment by n3farious** [comment]
@derekmurawsky I gave up and applied for a APRS-IS code. I had it within a few hours and forgot about the LotW cert.

**Comment by ge0rg** [comment]
@derekmurawsky have you tried the APK from https://github.com/ge0rg/aprsdroid/issues/136#issuecomment-245975776 or later? The About... dialog should show you the date.

Which exact app are you using for selecting the .p12 file? Is that from an email attachment or from the download folder? I've got an S4 mini and can try to setup the same scenario to see what happens  and why it doesn't work.

**Comment by derekmurawsky** [comment]
@n3farious - I applied for the password. Waiting for it to be approved. I do think the cert is worth it, though. 

@ge0rg - I used the app from the official site yesterday (1.3.0 2015-04-03), not the one from #136. I will try that later today. I downloaded the file via google drive and used the "my files" app to open it. A dialog then pops up and says "Extract Certificate" and prompts me for the password. This looks to be the system certificate handler, and not aprsdroid. The cert is then loaded into the android certificate store as a user cert. 

I would suggest that APRSDroid should either use the android cert store instead of its own, or support a more robust way to load a cert in. Thoughts there would be either

- An option in the settings menu to open the .p12 file 
- A Share With option, where I can select the file in my files, and select the Share icon, and then select aprsdroid there.

**Comment by derekmurawsky** [comment]
@ge0rg - Update, I installed the package from #136 and was able to install the certificate. However now there is a new issue. In the log I see

"Client Certificate not accepted: Self signed certificate in certificate chain."

I am connecting to ssl.aprs2.net

**Comment by ge0rg** [comment]
@derekmurawsky this message is generated by the APRS-IS server when it doesn't trust the client certificate. ARRL have changed their Root CA some time ago, and not all APRS2 SSL servers have added the new one to their trusted set. Unfortunately, I don't know which one(s) are still affected, I only got positive feedback from two sysops so far.

Please try configuring `northwest.aprs2.net` as the APRS-IS server.

**Comment by talisein** [comment]
I had the same issue, and installed the apk from https://github.com/ge0rg/aprsdroid/issues/136#issuecomment-245975776 and was able to import my certificate, and was also able to work ssl.aprs2.net. Thanks.

**Comment by jshank** [comment]
Version [1.3.0-19-g49ab077 2016-09-09](url=http://aprsdroid.org/download/builds/APRSdroid-gl-2016-09-09.apk) allowed me to import from Google Drive on my Pixel running the latest Android N release. Is there any way to see the certificate is configured in the app?

**Comment by ge0rg** [comment]
@jshank currently there is no way to see or remove the certificate via the configuration, but you will see it in the log if it is used. 

Closing this now with the 1.4 release.
