### ISSUE TITLE
APRSDroid will not send packets

### ISSUE THREAD

**Issue by kmerian** [ge0rg/aprsdroid#137]
I installed APRSDroid on a Moto G4 running android 6.0.1.  Activated it, I get "APRS Service started: Periodic GPS/Network Position, AFSK via Speaker/mic"

And a packet is never generated.

I had APRSDROID on my G3 and it ran flawlessly.

UPDATE:  Turns out it was an issue with my GPS receiver, not aprsdroid.  Thanks for the help, though!

**Comment by ge0rg** [comment]
Do you actually receive a GPS signal where you are? You can check with tools like GPS Status from Google Play.

For best results, you should be using the SmartBeaconing setting in APRSdroid (which will kill your battery). If lower precision is okay for you, you can enable "network location" in the periodic gps/network settings.

**Comment by ge0rg** [comment]
Any news here? Please check the FAQ: https://github.com/ge0rg/aprsdroid/wiki/Frequently-Asked-Questions#why-am-i-not-showing-up-on-aprsfi

**Comment by kmerian** [comment]
Solved.

Turns out at the time I was not getting a good GPS signal, and so it had no position to transmit.  Thanks for the help though.

**Comment by ge0rg** [comment]
Hi. Did you intend to re-open the issue?
