### ISSUE TITLE
aprsdroid newbie needs help!

### ISSUE THREAD

**Issue by samvein** [ge0rg/aprsdroid#140]
Trying to setup aprsdroid osm on my Nexus 7 1st  gen! Radio,Bluetooth (Mobilinkd TNC-2)connected and working! I can never get a map to load. My Nexus does not have a SDCARD slot. I've read may articles to no avail.  I've been dealing with this issue for more than a week! Any input or help would be greatly appreciated

**Comment by ge0rg** [comment]
Hi, there were some map loading problems in older builds of APRSdroid. Even without an SD card slot, you should have a /sdcard directory on the internal storage. Please get an up-to-date APK, i.e. the one referenced in https://github.com/ge0rg/aprsdroid/issues/101#issuecomment-193181580

Maybe you also need to try out a different file manager like Ghost Commander, see https://github.com/ge0rg/aprsdroid/issues/101#issuecomment-193425816

73 de Georg DO1GL

**Comment by samvein** [comment]
Thanks so much for the info!
Will do Georg
73
Dan
W3QL

**Comment by ge0rg** [comment]
The current APRSdroid builds have some more fixes for opening files. You should check them.
