### ISSUE TITLE
Location not shown on aprs.fi

### ISSUE THREAD

**Issue by kohhc1975** [ge0rg/aprsdroid#143]
I have a simple setup, where I connect a phone with aprsdroid apps directly to my handy radio via aux cable.
The GPS is well established and I can see my location as well as tracking on the aprsdroid map.

However, when I look into aprs.fi, I can't find my location or tracking data. I've gone through the settings but still can't find a solution..

Any suggestion anyone?

**Comment by ge0rg** [comment]
Please check the following, under "Radio":

https://github.com/ge0rg/aprsdroid/wiki/Frequently-Asked-Questions#why-am-i-not-showing-up-on-aprsfi

**Comment by kohhc1975** [comment]
Hi ge0rg,
I've done that actually, and the following is my status:

Radio:

Is your radio set to the correct frequency (144.390MHz in the Americas, 144.800MHz in Europe, other regions may vary)? YES, ITS CONNECTED TO 144.390Mhz.

Does your VOX circuitry work? Check the TX light on the radio when APRSdroid is sending! YES, MY VOX IS WORKING, AND FOR THIS PROBLEM IVE TESTED ON 3 DIFFERENT HANDY, ALL WORKING FINE IN APRSDROID, BUT LOCATION STILL CANNOT BE FOUND ON APRS.FI

Double-check with another radio set to the same frequency - are you hearing the AFSK "burp" sound? YES

Are you near to a digipeater or iGate that could forward your packets? YES. DOING TRACKING WITH YAESU FTM-100 WORKS PERFECTLY.

Common issues:

Do you have a good GPS reception (the GPS icon in the statusbar should be lighted permanently)? YES

Is APRSdroid generating position packets (green lines in the Log View, or your callsign appearing in yellow at the top of the Hub View)? YES. 

Are there problems sending out the position packets (check the status text in the Log View)? NO ERROR MESSAGES FOUND.

Can you see your packets in another APRS-IS client? NOT SURE HOW TO DO THIS. WILL APPRECIATE A GUIDE... THANKS IN ADVANCED.

Can you see your packets in aprs.fi's raw log? Please enter your full callsign with SSID! NO. MY CALLSIGN IS NO WHERE TO BE FOUND ON APRS.FI

IM RATHER NEW TO APRS THUS ANY HELP IS HIGHLY APPRECIATED.

**Comment by ge0rg** [comment]
> Are you near to a digipeater or iGate that could forward your packets? YES. DOING TRACKING WITH YAESU FTM-100 WORKS PERFECTLY.

Are you seeing your APRSdroid instance on the FTM-100, or are you seeing what your FTM-100 sent on aprs.fi? If the FTM-100 can see your APRSdroid packets, your installation is technically okay.

aprs.fi is a web portal to APRS-IS, which only sees what is delivered to an iGate. If you have no iGates and no digipeaters in your neighborhood, your packets have no way to get onto APRS-IS and won't be shown on aprs.fi. That means you need to go near an iGate to test the function, or set up one yourself.

**Comment by kohhc1975** [comment]
No.
What I mean is aprs.fi can see my FTM-100, but cannot see my aprsdroid.
MY FTM-100 also cannot see my aprsdroid.

There are 1 digirepeater and 1 igate near my place, the nearest one is just 1 km away... so I believe it should be fine...

**Comment by ge0rg** [comment]
Alright. Can you hear the APRSdroid transmission when tuning the FTM-100 to APRS freq? Does it sound like a typical AFSK transmission? Is the volume okay? You might need to increase the "Frame Sync Prefix" in APRSdroid's TNC settings if your VOX is a little slow.

Your handy probably has a much lower TX power and a worse antenna than the FTM-100, so bridging the 1km distance to the igate might still be challenging. However, you should be able to have the FTM-100 decode the APRSdroid positions once everything is set up properly.

**Comment by kohhc1975** [comment]
Ok, will verify that...
Btw, can you describe a bit on the sound of AFSK transmission? Is it something like the fax machine sound?

**Comment by kohhc1975** [comment]
MY current setting for Frame Sync Prefix is 200ms.
What do you suggest?
FYI, my handy is a 5W handy..

**Comment by ge0rg** [comment]
200ms is probably too short. Try increasing to 500ms or maybe even 800ms. Once it works, you should set the lowest value where you are able to decode the packets with the FTM-100.

**Comment by kohhc1975** [comment]
Tried until 90's but still fail to reach aprs.fi.
Will try again soon using mobile rig and antenna instead of handy, just to confirm if the apps is set up correctly...

**Comment by ge0rg** [comment]
There are many possible error causes between the app and "aprs.fi", you really need to find somebody with an APRS radio to double-check the local situation.

**Comment by rockaclimba** [comment]
Its very discouraging - very possibility of sending your location using a cable-radio-celphone was very exciting ...
But its not that easy .. I am not able to register my location at aprs.fi though i croschecked with second radio - TX from baofeng is correct. 
Cellphone do not show RX data - why? I dont know ...
I used VOX 5, SQL 1 

and I use 500ms in App 

Able to see RED LIGHT flas when I press SEND POSITION and this position is captured by another radio - but this position is not going to aprs.fi 
So - I have two issues...

1. Not been seen on APRS.FI 
2. Not seeing received packets

**Comment by IU5RCF** [comment]
Hi rockaclimba, I have the same problem, with APRSdroid on cellphone P8lite and a radio Radtel RT-490. Until 1 month ago it worked.  Now I see  correct logs on APRSdroid but I can't see my position on aprs.fi
How have you resolved this problem ?

**Comment by ge0rg** [comment]
APRSdroid can only send your position to the radio frequency. You need to have an i-gate close enough to receive your packet for it to appear on APRS-IS and thus on aprs.fi, or a repeater that will forward it to the next i-gate.
