### ISSUE TITLE
OutOfMemoryError in AFSK decoder

### ISSUE THREAD

**Issue by emiliogon** [ge0rg/aprsdroid#144]
The app has crashed a couple times now while monitoring with the regular demod (not HQ) and audio AFSK.  I just saw it now, APRSdroid just disappeared without a crash notification.  There is no error listed in the app's log.

This is a Galaxy Nexus running Cyanogen 12.1; it was externally powered and in airplane mode with Wi-Fi enabled.

APRSdroid is _not_ configured to send packets, I was only monitoring.  logcat was running, but I've seen this do it without it.

Here is the logcat from around the crash:
[aprsdroid-lowQdemod-crash-logcat.txt](https://github.com/ge0rg/aprsdroid/files/437666/aprsdroid-lowQdemod-crash-logcat.txt)

**Comment by ge0rg** [comment]
The relevant part of the log is this:

```
E/art     (18082): Throwing OutOfMemoryError "Failed to allocate a 160 byte allocation with 4 free bytes and 4B until OOM" (recursive case)
E/art     (18082): "AudioBuffeProcessor" prio=5 tid=14 Runnable
E/art     (18082):   | group="main" sCount=0 dsCount=0 obj=0x22c09100 self=0x43027798
E/art     (18082):   | sysTid=18101 nice=0 cgrp=default sched=0/0 handle=0x42bae0a8
E/art     (18082):   | state=R schedstat=( 45677276582 16962158211 47982 ) utm=4480 stm=86 core=0 HZ=100
E/art     (18082):   | stack=0x5562c000-0x5562e000 stackSize=1036KB
E/art     (18082):   | held mutexes= "mutator lock"(shared held)
E/art     (18082):   at android.os.BaseBundle.<init>(BaseBundle.java:67)
E/art     (18082):   at android.os.BaseBundle.<init>(BaseBundle.java:76)
E/art     (18082):   at android.os.Bundle.<init>(Bundle.java:51)
E/art     (18082):   at android.content.Intent.putExtra(Intent.java:6163)
E/art     (18082):   at org.aprsdroid.app.AfskUploader.notifyMicLevel(AfskUploader.scala:96)
E/art     (18082):   at org.aprsdroid.app.AfskUploader.peak(AfskUploader.scala:92)
E/art     (18082):   at com.jazzido.PacketDroid.AudioBufferProcessor.run(AudioBufferProcessor.java:84)
```

It fails to allocate more RAM. I've heard of CM12 having some memory leaks. Maybe you need to reboot your phone for this not to happen any more?

**Comment by emiliogon** [comment]
I'm a couple builds old on CM, so I'll try updating, restarting, and testing.

**Comment by ge0rg** [comment]
Maybe the Galaxy Nexus is just not powerful enough for CM12. It was the last phone where I really liked the form factor, but I haven't used mine for over a year now...
