### ISSUE TITLE
fix website link for mapsforge maps download

### ISSUE THREAD

**Issue by tedder** [ge0rg/aprsdroid#147]
Your page:
https://aprsdroid.org/osm/

There is no FTP server; looks like this is the replacement:
http://download.mapsforge.org/maps/

Also, "latest available" links to a version that isn't tagged OSM. It downloads `APRSdroid-gl-2016-08-03.apk`.
https://aprsdroid.org/osm/apk

**Comment by ge0rg** [comment]
Thanks for the feedback!

I've updated the mapsforge link and added another to OpenAndroMaps. Unfortunately I couldn't reproduce the "latest available" issue, as it's now pointing to the latest OSM build. From the sources, it should always direct to a _osm.apk.
