### ISSUE TITLE
Feature: Display Position Coordinates in Lat and Long

### ISSUE THREAD

**Issue by Proeliator** [ge0rg/aprsdroid#148]
Displaying the position that was received in the Station Info would be extremely useful, especially for packets that contain the compressed position format. 

I use APRSdroid for tracking balloon payloads. During those times when the balloon decides to vacation in a wooded valley with no digipeaters in range the app is one of the few solutions that allows us to get the final position on foot. With Lat and Long it would make it much easier to disseminate the position among the group and plug it into dedicated navigation hardware. (especially with compressed position)

Unless. of course, there's a simple way to do it and I just don't know how!

**Comment by ge0rg** [comment]
I'm pondering about adding a "Share..." or "External map..." link to the station menu, that would open the coordinates in Google Maps (or any other mapping app you have installed). It would work with the last position heard from the station. Does that sound acceptable to you?

**Comment by ge0rg** [comment]
Update: I've added an "External map" option to the station view and station context menu, it will now open a `geo:lat,lon?q=lat,lon(callsign)` link, which can be processed by Google Maps (hiding the coordinates) or the venerable [GPS Status](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2), which will show a radar with full coordinates.

**Comment by Proeliator** [comment]
Thanks a bunch! This was precisely what we needed. I hope it wasn't too difficult to implement. I knew that the app was correctly interpreting the position from the packet because it was in the correct place on the in-app map, so thanks for letting the position be able to be exported like so. 

I'll have to test with our balloon radios but it seems like this will do what we need (have downloaded and running, like the new UI look btw). Good insight on also using the radar for GPS status, it's something we already use!

Thanks again! Had a launch this weekend, landed in a field this time. W3EAX-8 is the balloon's callsign if you're ever curious. about tracking us on aprs.fi

**Comment by ge0rg** [comment]
Glad I could help you! The feature itself wasn't hard at all, actually I had made a preliminary version more than a year ago, but it wasn't properly working with all external apps, so I had to put it on hold.
