### ISSUE TITLE
java:io.IOException error with bluetooth device

### ISSUE THREAD

**Issue by JDogHerman** [ge0rg/aprsdroid#150]
I am having this same issue as #126 

I am using an LG Phoenix 2 with a Moblinkd TNC2 over bluetooth. I have unpaired & paired the bluethooth, Removed the moblinkd app and restarted the phone with starting only aprsdroid.

I am getting the same error: java.io.IOException: read failed, socket might closed or timeout, read ret: -1

My android version is 6.0 patch level=2016-07-01 with Kernel=3.10.49
APRSdroid is on v1.3.0 2015-04-03
Attached is a screenshot from the logs.

Any ideas for a solution?

![capture _2016-12-01-13-17-10](https://cloud.githubusercontent.com/assets/1299282/20806400/ba5144ce-b7c8-11e6-9505-6fd538dc93f3.png)

**Comment by ge0rg** [comment]
That means there is a communication problem with Bluetooth at the operating system level. Possible causes:

* TNC is already connected to a different device or different app (maybe your PC)
* TNC is off / too far away
* Your android can't open any more bluetooth connections

You should be able to cross-test the issues by either:

* trying to connect the TNC from a PC / other device
* trying to connect the TNC from a Bluetooth terminal app or the MobilinkD config app on your Android

**Comment by nickparker75** [comment]
Same issue here exactly

**Comment by realvespaholic** [comment]
Hey had the same problem, with the mobilinkd tnc. Apparently you can't have it connected to the mobilinkd app and the aprsdroid app at the same time. I 'disconnected' my mobilinkd tnc from the app and  everything was fine when I started it up in aprsdroid.

Hope this helps!

**Comment by ge0rg** [comment]
@nickparker75 @JDogHerman were you able to solve your problem by disconnecting the Mobilinkd app?

**Comment by ge0rg** [comment]
It looks like this error message was super-confusing, so I've improved the wording when connecting via Bluetooth:

![image](https://cloud.githubusercontent.com/assets/165635/25902975/609e25d6-359b-11e7-9d79-bc8e4da88e7b.png).
