### ISSUE TITLE
TODO for version 2.0

### ISSUE THREAD

**Issue by unzihe** [ge0rg/aprsdroid#151]
Multiple parallel backends
I-Gating

When can be achieved?

The best is the Bluetooth TNC + internet (aprs-is) with the send function, priority development

Mainly used in rescue teams, there is a certain amount of practical value.

BG5DNS

**Comment by ge0rg** [comment]
Yeah, I have these things on my agenda... Not sure if I'll allow multiple backend configurations other than (Bluetooth/USB/local TNC) + (APRS-IS), but that should be usable for iGating.

Please follow this issue for iGate support: #29
