### ISSUE TITLE
Display altitude, and copy decoded object position to clipboard

### ISSUE THREAD

**Issue by verox-syrion** [ge0rg/aprsdroid#153]
Im planning to use aprsdroid to High altitude and radiosonde balloon chase.
I've made dsp based TNC (with bluetooth add-on) which can decode AX.25 AFSK/GMFSK and vaisala RS41 radiosonde.

https://www.youtube.com/watch?v=FLhHM-NY4gI

Unfortunetly aprsdroid does not provide decoded lat/lon values for selected object. Can You add simple feature? By tapping on the station info - add button copy lan/lon into clipboard? That would be very helpfull Altitude decoding would be also nice.

73!s Tom SP9UOB

**Comment by ge0rg** [comment]
The current 1.4 beta provides an "External map" option in the station view. It will share the geo: URI with whatever mapping app is installed, e.g. Google Maps or GPS Status/Radar.

Does that come sufficiently close to what you desire?

What do you intend to do with the text in the clipboard? Store it for later use? Maybe a log / export would be more handy then?

**Comment by verox-syrion** [comment]
Awesome! Thats even better, I can now export exact position of balloon payload and go for it :-) 
My intention with clipboard was simple, copy position, and paste it into another app. 

Log/export feature also would be nice. 

Thanks! 

73s, Tom SP9UOB.

**Comment by ge0rg** [comment]
Great that the feature works for you!

Log export is tracked in #129, and I have decoding of additional station info somewhere on my 2.x agenda, but there is nothing specific yet.
