### ISSUE TITLE
Reuse of OSM maps

### ISSUE THREAD

**Issue by skidoo** [ge0rg/aprsdroid#155]
I have tried with some of the Android GPS apps with OSM support to use the maps that aprsdroid uses, or use maps that those apps use with aprsdroid and no luck.  Would be nice to use the same map files for aprsdroid and a routable GPS app to save a bunch of space.   Are there any apps that can share maps with aprsdroid.  Seems like a file format issue, but maybe there are other limitations.

Edit:  Since posting, I have found that Cruiser works with the same map files, but OSMAnd does not.

**Comment by ge0rg** [comment]
APRSdroid is using the "mapsforge" format internally, which is also supported by c:geo (not quite a nav app, but it allows map sharing).
