### ISSUE TITLE
APRSdroid passcode

### ISSUE THREAD

**Issue by nb1914** [ge0rg/aprsdroid#161]
Hello,

Can anyone please provide a valid passcode to use APRSdroid i have purchased the app officially from google play. initially the APRSdroid team requested identification of my ofcom certificate. I havnt been able to locate this but did send a photo of my ofcom license screen via my ofcom account. I have sent several emails for an update with no response. I know there are passcode generators out there but would prefer to do things correctly. 

call sign 2E0BNL

**Comment by ge0rg** [comment]
Hi Andy,

we are required to manually verify that you, the owner of the above email address, are actually the radio amateur with the given callsign. Unfortunately, a screenshot excerpt that might come from an official database (and might be accessible to anybody on the Internet) does not help with that. We need something that proves that you are actually the owner of the license.

You can also ask an iGate operator in your neighborhood to calculate the passcode for you - or use a passcode generator. The end result is the same ;-)
