### ISSUE TITLE
Get Error Aprs Service has shut down, 

### ISSUE THREAD

**Issue by rchapman4697** [ge0rg/aprsdroid#164]
Keep getting error APRS Service has shut down, when trying to to use with Mobilinkd modem, tried three different phones, getting ready to get a refund on the mobilinkd modem since it wont work. Also when you select to modem in the preferences, for the audio output, the audio still come out of the speaker on the phone and the radio does not key. Nothing but problems with this.

**Comment by ge0rg** [comment]
You need to set APRSdroid's connection type to Bluetooth TNC, not to AFSK.

1. Pair the Mobilinkd with APRSdroid from Android's Bluetooth prefs
2. Set APRSdroid to Bluetooth TNC and select the right Bluetooth device for the Mobilinkd
3. "Start tracking"

If you encounter further problems, please enable "Connection logging" and provide a screenshot of the log view. Thanks & 73!

**Comment by rchapman4697** [comment]
I did set it to Bluetooth TNC, but where do you go to set the right audio channel and also how do you fix the APRS has shut down error?

**Comment by rchapman4697** [comment]
Still getting APRS service stopped error message. How can I fix that?

**Comment by rchapman4697** [comment]
Here is the error message I got on the screen....java.io,IOEException:;read failed, socket might closed or timeout, read ret:-1

**Comment by rchapman4697** [comment]
That error comes right after the APRS Service Stopped.

**Comment by ge0rg** [comment]
This looks like #150 - do you have the Mobilinkd app in the background, connected to the TNC?

Unfortunately, only one app can be connected to a Bluetooth device at the same time.

**Comment by ge0rg** [comment]
There is now a better error message in https://aprsdroid.org/download/builds/APRSdroid-gl-2017-05-10.apk - please follow up the discussion in #150.

**Comment by rchapman4697** [comment]
Unfortunatley I sold the Mobilinkd Got tired of trying to get it to work.
