### ISSUE TITLE
Open source build for F-Droid

### ISSUE THREAD

**Issue by tomikmar** [ge0rg/aprsdroid#168]
Hi, I created an issue to add APRSdroid to F-Droid repository:
* https://gitlab.com/fdroid/fdroiddata/issues/722

It looks that content of https://github.com/ge0rg/aprsdroid/tree/master/libs is provided without source code. Could you please clarify if these libs are open source and if so where the source code is?

**Comment by ge0rg** [comment]
I have commented on gitlab/f-droid, please follow up there :)
