### ISSUE TITLE
Feature Request Change Version in APRS Packet

### ISSUE THREAD

**Issue by stephensworld** [ge0rg/aprsdroid#171]
Hi,

is it possible to change APDR* to something else if using Bluetooth or Cable connection? Or change it manually in the gui?
Reason: There are some OM who are filtering e.g. APDR13 because they would like to see only real HF transmissions. Many APRDdroid users use TCP/IP.

I use APRSDroid with HC-05 dongle to control the TM-D710 TNC. Nice solution!

Thanks
Stephan

**Comment by ge0rg** [comment]
No, the tocall is something assigned globally to APRSdroid. However, you can easily analyze the path of the packet - if it contains "TCPIP*", it is an APRS-IS packet - http://www.aprs-is.net/Connecting.aspx

**Comment by na7q** [comment]
There are ways to change it, if necessary. I have mine custom set to "APRS".
If you want to know how to change this, I can help you do it. Just shoot me a reply.
