### ISSUE TITLE
Ability to change the number of 'flag

### ISSUE THREAD

**Issue by mpannen1979** [ge0rg/aprsdroid#172]

**Comment by mpannen1979** [comment]
Seems that the AFSK is sending maybe one 'flag' (0x7e) byte at EOT. 

My though is that being able to tweak the number of 'flags' at EOT might increase transmission reliability.  


Mobilinkd looks like it sends 46! of them (seems excessive), but the Mobilinkd seems to be received better for some reason.

**Comment by mpannen1979** [comment]
I made the tweak and does not help.  There is something different between AFSK and Mobilinkd that one digipeater can hear it and one cannot.

**Comment by ge0rg** [comment]
Is it possibly some audio attenuation problem with the different AFSK frequencies? I'm a real signal processing newbie, so I can't really say what it could be.

**Comment by mpannen1979** [comment]
Ultimately, this was an issue with audio levels between my smart device and the tnc interface.  Mic input to radio was too hot.
