### ISSUE TITLE
Error connecting with SSL certificate

### ISSUE THREAD

**Issue by lumag** [ge0rg/aprsdroid#174]
I was using SSL certificate to connect to APRS network. Recently SSL server started returning 'self signed certificate in certificate chain' error.

![screenshot_2017-06-17-23-51-19](https://user-images.githubusercontent.com/20323/27256297-361ebad2-53b9-11e7-906b-8af63c6e0ba5.png)

**Comment by ge0rg** [comment]
That sounds like the server you are connecting to does not accept the current LoTW Root CA. Could you please enable connection logging in APRSdroid and note the exact server name (something like `T2SJC`) that is reported with the error?

**Comment by lumag** [comment]
Connection logging is enabled. I'll try rebuilding APRSdroid to add IP address to log messages.

**Comment by ge0rg** [comment]
Rebuilding shouldn't be necessary. There are only two servers in the SSL rotate right now, you will be faster trying them manually:

    northwest.aprs2.net has address 44.24.241.98
    
    sjc.aprs2.net has address 198.137.202.21
    sjc.aprs2.net has IPv6 address 2607:7c80:54:1::21

**Comment by lumag** [comment]
T2USANW works. Other one does not.

**Comment by ge0rg** [comment]
Could you please re-try SJC? I've talked to the admins, and they installed the new LoTW root. However, neither of us have a recent LoTW certificate, so we were not able to test :)

**Comment by lumag** [comment]
SJC works now, thank you.
