### ISSUE TITLE
feature request: packet radio terminal mode 

### ISSUE THREAD

**Issue by stephensworld** [ge0rg/aprsdroid#175]
Hi,

it would be great to have a packet radio terminal in aprsdroid.
At the moment I restart my TNC and use a BT serial terminal App to communicate with TNC in command mode. It works but it is not a nice solution. 
If aprsdroid would have this feature I could simply stop tracking, go the menu and I have a pr terminal. 
TNC is still in kiss mode and I don't have to restart TNC and use BT terminal apps where I have to set e.g. callsign every time. A possibility to send files in didadit or autobin mode could be made in future versions.

There are still many PR digipeater which could be used with such a feature in aprsdroid.
Hardware could be every TRX with TNC in kiss mode, Kenwood TH-D7 with USB serial adapter or BT HC-05, TH-D72....

I think much work is already done for this feature in aprsdroid (great GUI, communication BT or USB serial, kiss frames, messages...)

Thank you very much.

Best regards 
Stephan

**Comment by ge0rg** [comment]
APRS is using a very small subset of AX.25, and aprsdroid only implements that subset. Creating support for connections and state tracking that's required for PR would be a significant feat, probably more so than the required UI. 

Unfortunately, I hardly find the time to implement APRS related features, so PR is far out of scope. Sorry!
