### ISSUE TITLE
Request for nojit offline map (osm) build of latest release 

### ISSUE THREAD

**Issue by jweisert** [ge0rg/aprsdroid#183]
At your convenience, could you please build a "nojit" offline (osm) version of the new 1.4 release? My cheap Chinese Android phone doesn't seem to like the regular offline code.

**Comment by ge0rg** [comment]
1.4 APK without JIT rendering: https://aprsdroid.org/download/builds/APRSdroid-gl-2017-08-04_osm_nojit.apk

Have fun :)

**Comment by jweisert** [comment]
Hello Georg,

Thanks very much for the very fast response!

Jim Weisert
