### ISSUE TITLE
When the system language is set to Arabic, the sent packets are discarded

### ISSUE THREAD

**Issue by ha5dzs** [ge0rg/aprsdroid#186]
I set my phone to Arabic (to learn the language), and I noticed that the GPS coordinates have the Arabic numerals instead of Latin script. As a result, I no longer see my callsign on aprs.fi.

You can replicate this by switching your device to Arabic, and try starting beaconing when you have GPS fix.

**Comment by ge0rg** [comment]
This is probably a missing locale setting in the position formatting code. I'll check the code and try to fix this.

**Comment by ge0rg** [comment]
Thanks for pointing this out. I found and fixed multiple places where the local language was used instead of the neutral one meant for APRS.

Please [test this APK](https://aprsdroid.org/download/builds/APRSdroid-gl-2018-10-21.apk) and let me know if there are other issues.
