### ISSUE TITLE
support for dmr/uhf/vhf radio enabled smartphone (e.g. rfinder)

### ISSUE THREAD

**Issue by kf7rcs** [ge0rg/aprsdroid#187]
aprsdroid to support uhf/dmr enabled smartphones like rfinder, S15, etc.

**Comment by ge0rg** [comment]
APRSdroid should be running on those devices, just not directly using their RF module. Unfortunately, the Chinese tech is very badly integrated and documented....

I did do some attempts with the Runbo X5, but it was more or less a dead end :(

**Comment by kf7rcs** [comment]
roger thanks for the attempt!

**Comment by bobofthedeep** [comment]
Hi Georg....been trying to get you for a while...I sent you the api's to do this months ago...did you receive? Please get ahold of me on FB Messenger search w2cyk, sms/telegram/signal/WhatsApp +1.631.830.2555 we have an intenet for PTT and api to redirect the kiss modem output to the exciter and grab radio audio output to feed into the modem. Also an intent to change F. We created these just for this purpose ;) Looking forward to hearing from you! It was great meeting you last year in F'hafen....I can send you a radio to work with.  De Bob W2CYK

**Comment by ge0rg** [comment]
@bobofthedeep I'm really sorry I didn't come back to you yet. It's still a super-busy time for me, and I need to fix the Android 10 issues in APRSdroid first, before I can move on with adding support for further backends. It's not forgotten, but with my current time budget I'm only making veeeery slow progress, unfortunately.
