### ISSUE TITLE
Need help locating iGate operator or any other assistance for a passcode

### ISSUE THREAD

**Issue by lawman1841** [ge0rg/aprsdroid#189]
I'm slowly getting back into ham radio after a long absence and recently bought the APRSdroid app for my Galaxy S6.  I've been unable to find any local hams who know anything about APRS-IS and have been unable to find out how to locate and contact an iGate operator who might help me get a passcode.  Any help you might offer will be greatly appreciated.

**Comment by dBitech** [comment]
enter your CALLSIGN-SSID  into: http://n5dux.com/ham/aprs-passcode/ and it
will provide you the passcode you need.

**Comment by lawman1841** [comment]
Thank you.

**Comment by lawman1841** [comment]
Does the passcode need time to work its way into the system?  Wondering why I don't show up on aprs.fi.

**Comment by ge0rg** [comment]
Once you enter the correct passcode, packets from APRSdroid will be sent to APRS-IS and to all services consuming it, including aprs.fi. You need to reconnect in APRSdroid, but besides of that it is immediate. Maybe you were having a technical problem with the APRS-IS server?
