### ISSUE TITLE
Can't enter lowercase characters in name field for messages

### ISSUE THREAD

**Issue by DC7IA** [ge0rg/aprsdroid#190]
Hello,

just tried APRSdroid on a friend's Samsung Galaxy S6 (SM-G920F).

Current Behaviour: 

I am not able to enter any other characters than the numbers 0-9 into the sall sign field for messages.

This makes it impossible to send text messages to anyone.

Expacted behaviour:

It should be possible to enter any character from the alphabet and numbers.

App version: 

Android version: 7.0
Device model: Samsung SM-G920GF

First occured: all builds / today

Steps to reproduce:

1. Install app on SM-920GF
2. Try to compose a message.
3. I'm unable to enter letters.

**Comment by DC7IA** [comment]
Update: I can only type in upper case characters. APRSdroid doesn't accept lower case characters at all.

IF you know that: you can send messages. But if not: You will give up after some tries.

**Comment by ge0rg** [comment]
Fixed now. Please test the [nightly APK](https://aprsdroid.org/download/builds/APRSdroid-gl-2018-10-22.apk).
