### ISSUE TITLE
WX Decoding

### ISSUE THREAD

**Issue by Greentwins1** [ge0rg/aprsdroid#197]
Sorry new to APRS droid but it would appear it does not decode WX data and display. Is that correct or am I missing something.
Thanks in advance.

**Comment by ge0rg** [comment]
You are right. Right now, APRSdroid does not support decoding WX and most other non-position data. This is a feature that first needs to be implemented in https://github.com/ab0oo/javAPRSlib and then have a UI added. There is already an issue open for WX, #39, so I'd like to close this one. Please use #39 to track the non-progress of this feature. ;)
