### ISSUE TITLE
New offline map link

### ISSUE THREAD

**Issue by caseydiers** [ge0rg/aprsdroid#211]
Just came across this site and it quickly and easily creates custom areas of offline maps that are compatible with the offline version and it can make relatively large area at a time.  You might add a link to this site o  the offline web page. 

https://extract.bbbike.org

**Comment by Nahannidog** [comment]
Casey,
Wow, what a great tool!
Have you been able to generate mapsforge fomat maps for APRSDroid that include contour-lines?  I have been unable to so far.  Thanks!

**Comment by caseydiers** [comment]
Not sure. I live in Chicago. We don't have 'contour' here!

**Comment by ge0rg** [comment]
Thanks very much, I've added a link to the OSM info page! :D
