### ISSUE TITLE
APRS digi path stopped accepting Android screen keyboard input

### ISSUE THREAD

**Issue by TheButterZone** [ge0rg/aprsdroid#226]
I got the vibration for each letter I tried to press into the path, but nothing would show up. Other fields accept Android screen keyboard input, so I typed WIDE1-1,WIDE2-1 into one of them, selected that, cut & pasted it over into APRS digi path. Persisted through power cycling.

**Comment by ge0rg** [comment]
Was your keyboard set to uppercase letters? I thought I had fixed the issue in 88408aedf3241bd5d528b1a344daf50307f0d73e, but that didn't affect the digi path. I have now committed a fix, but the code base is in the middle of a refactoring, so I'm not able to build a new APK today.

**Comment by TheButterZone** [comment]
Nope, guess the shift icon needs to be double-tapped to lock it in so all input will be accepted.

**Comment by ge0rg** [comment]
The new APK containing the fix is https://aprsdroid.org/download/builds/APRSdroid-gl-2019-03-16.apk
