### ISSUE TITLE
No 'Map File Name' and 'Theme File Name' options

### ISSUE THREAD

**Issue by CChatzis** [ge0rg/aprsdroid#237]
Hi,

just downloaded APRSDroid and trying it out with Mobilinkd TNC. I want to use offline maps (main reason I chose APRSDroid), but no option seems to be in the Preferences; the Menu 'Display and Notifications' ends with the submenu 'Notifications' (cannot scroll more down). Not even the submenu 'Theme file name'.
I am using an old Samsung GT-I8260, running Android 4.1.2. Also APRSDroid version is 1.5.0. (In Greek)

Any ideas what's going wrong? Thanks in advance.

**Comment by ge0rg** [comment]
You need to download the `_osm` version of APRSdroid, not the regular one. Latest OSM build is https://aprsdroid.org/download/builds/APRSdroid-gl-2018-11-18_osm.apk
