### ISSUE TITLE
Crashes upon launch on Android 10 devices

### ISSUE THREAD

**Issue by GrecoJava** [ge0rg/aprsdroid#242]
The app immediately crashes upon launch.

Android 10 devices tested:
- Pixel XL
- Pixel 2 XL
- Pixel 3 XL

**Comment by Danie10** [comment]
It seems to crash on my Pixel 2 XL with Android 10 when I try to open the map view. After that, it crashes all the time on startup. I reset the app and did not open the map view, just watched the log and changed preferences and it seemed to stay running fine with the track transmitting. Its a workaround for now but at least I can use the app.

**Comment by ge0rg** [comment]
Yeah, android 10 has removed a part of the old Google Maps library, making aprsdroid crash. This problem will be tracked in #233. I've written more about tut reason in https://github.com/ge0rg/aprsdroid/issues/233#issuecomment-531451892

**Comment by Danie10** [comment]
Thanks @ge0rg I've installed the OSM version for now and downloaded the offline maps - working fone for now. Seems the issue on v10 Android is the call to Google Maps.
