### ISSUE TITLE
7 character callsigns no longer accepted

### ISSUE THREAD

**Issue by CountParadox** [ge0rg/aprsdroid#244]
Hello,

Previously 7 character callsigns such as those uses here in Australia, have been accepted by the app, however now they are cut down to 6 characters, and thus my aprs passcode does not work.

Please can the 6 character limit be increased back up so that I can continue to use the app....

**Comment by CountParadox** [comment]
Note; this did work for apes.fi, my 7 char sign correctly worked on the website.

**Comment by CountParadox** [comment]
I understand this is due to the ax.25 spec being strictly for 6 char callsigns, however there are many other stations using invalid calls, over TCP/ip, which is perfectly legal and fine.

**Comment by ge0rg** [comment]
The limit was raised shortly after the release. Please use one of the later builds, e.g. https://aprsdroid.org/download/builds/APRSdroid-gl-2019-03-16.apk

**Comment by CountParadox** [comment]
Working now, thank you!
