### ISSUE TITLE
update developer for android?

### ISSUE THREAD

**Issue by abdazzamajhari** [ge0rg/aprsdroid#254]
helo, any update for make it build successfully?

**Comment by penguin359** [comment]
I've documented my efforts in getting it to build in issue #274 . Check that out and see how far you can get. If you have any issues, please post a detailed error message in your response so we can see where it's going wrong.

**Comment by abdazzamajhari** [comment]
> I've documented my efforts in getting it to build in issue #274 . Check that out and see how far you can get. If you have any issues, please post a detailed error message in your response so we can see where it's going wrong.

nice, i will check it. thanks!
