### ISSUE TITLE
Consistently crashing on Android 10

### ISSUE THREAD

**Issue by fattmox** [ge0rg/aprsdroid#256]
Once configured, crashes when map is loaded. Then always crashes when opens. Has worked seemlessly in the past on the same hardware.
Have tried both the Google Play store version and the latest APK

![Screenshot_20200223-144656](https://user-images.githubusercontent.com/11093904/75121961-28ca3600-564e-11ea-89a3-1dab824f094c.png)

**Comment by jefwks** [comment]
> 
> 
> Once configured, crashes when map is loaded. Then always crashes when opens. Has worked seemlessly in the past on the same hardware.
> Have tried both the Google Play store version and the latest APK
> 
> ![Screenshot_20200223-144656](https://user-images.githubusercontent.com/11093904/75121961-28ca3600-564e-11ea-89a3-1dab824f094c.png)

I'm seeing the same issue.  Updated to version 10 this morning on my Samsung Galaxy S9.  APRSDroid hasn't worked since.  Never had a problem before this update.

**Comment by jefwks** [comment]
So does the developer have any timeline for dealing with this?

**Comment by ge0rg** [comment]
This has been a major issue with Android 10 indeed. I've provided a new build on Google Play Beta and a new APK on the webserver, please see https://github.com/ge0rg/aprsdroid/issues/233#issuecomment-575652508 for details.
