### ISSUE TITLE
1200 baud not on the list for KISS TNC

### ISSUE THREAD

**Issue by WP3BM** [ge0rg/aprsdroid#257]
Greetings, 

There is no option for 1200 baud for the TNC KISS USB Serial. Our APRS network is based on VHF using 1200 baud. Can this be added? Thanks!

**Comment by ge0rg** [comment]
1200bd is the only RF baud rate that's currently supported by APRSdroid. The baud rate you can configure in the USB-serial options is only for the (emulated) serial port, not for the APRS emissions. 

The actual RF baud rate needs to be configured in the TNC, using the respective configuration tools. If there is a serial protocol to configure that, you can add a TNC init string to ensure the right settings. But as most TNCs are also configured to 1200, no further steps should be needed.
