### ISSUE TITLE
message to aprs station

### ISSUE THREAD

**Issue by oh5bzr** [ge0rg/aprsdroid#258]
hi,

it could be cool to just click heard aprs station and select send message!

Also separate send message by call sing.

aprs iGate supports that.

joni

**Comment by ge0rg** [comment]
You can tap the arrow button in the station view action bar to send a message:

![Screenshot_20200412-184314_APRSdroid](https://user-images.githubusercontent.com/165635/79074582-8c3b2080-7ced-11ea-8817-3ec12d8d1830.jpg)
