### ISSUE TITLE
screen awake doen't work at every view/activity

### ISSUE THREAD

**Issue by iddq** [ge0rg/aprsdroid#260]
for example it works at APRSdorid Hub
but it doesn't work at Station Information (in APRSdorid Hub)

**Comment by ge0rg** [comment]
I've now published APRSdroid 1.6 to Google Play ([direct APK download](https://aprsdroid.org/download/builds/aprsdroid-gl-2020-08-28.apk)). All activities except for preferences will keep the screen on now.
