### ISSUE TITLE
Offline Maps not working on Samsung 10.1 Tablet

### ISSUE THREAD

**Issue by kruegdr** [ge0rg/aprsdroid#265]
Hello, I've been looking through documentation and posts for most of the day and I still can't get the offline maps working. I've installed Ghost Commander, rebooted the device many times, and tried several different builds. I've got AdvancedMapViewer on the device, and am able to open the *.map files in that application without issue. I've placed the *.map files in the highest level of the external and internal SD cards, but APRSDroid still isn't able to load the maps.

Samsung GT-N8013
Android version : 4.1.2

APRSDroid OSM Builds I've tried:
2016 09 17
2016 10 06
2016 12 02
2017 04 26
2017 07 28
2018 11 18

**Comment by kruegdr** [comment]
Didn't realize how old the Android version was. I loaded 2012 10 12 and got it working.

**Comment by na7q** [comment]
Download the 2020 build. Shouldn't have any problems then.
