### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by comschmid** [ge0rg/aprsdroid#266]
Hi,
After I pressed a wrong button at the top (sorry, I don't remember exactly, which one at the top), the application keeps crashing at each the start. This is probably because the start page was persisted, and now it always throws an exception upon start. Let me know if I should send a log file for debugging.
Thanks!

**Comment by ge0rg** [comment]
Hi, this is a problem with the old version of Google Maps that APRSdroid is using. There is a workaround using OSM maps on Google Play [beta channel](https://play.google.com/apps/testing/org.aprsdroid.app) and [available as APK](https://aprsdroid.org/download/builds/aprsdroid-gl-2020-01-01.apk).
