### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by Exscotticus** [ge0rg/aprsdroid#267]
Is there a way to get the app to track without an Internet connection? Obviously I'm not talking about APRS-IS. And I don't mean offline maps, either.

I'm simply talking about the app being able to perform its TNC duties without a network connection. GPS service—yes. Internet—no.

**Comment by ge0rg** [comment]
By default, the app will use APRS-IS and Google Maps, both requiring a mobile data connection. If you set up a different connection type like AFSK or a Bluetooth TNC, this part doesn't need Internet and will work offline.

**Comment by Exscotticus** [comment]
I was initially getting error messages when I tested offline. I did not retest after I switched to audio. Testing now, I can confirm no issues. Thank you!
