### ISSUE TITLE
APRSdroid built for an older version of Android...

### ISSUE THREAD

**Issue by KM6HVW** [ge0rg/aprsdroid#271]
Hello, 

My phone recently updated to a newer version of Android. Ver. 10. Kernel 4.14.117-perf+ #1 Build number QDF30.130-42-5. After the update I get a message saying this app is built for an older version of Android and may not work correctly. Indeed it doesn't. The App crashes when I try to open map view among other things. Many of the updates to Android were security related and necessary. Are there any plans to accommodate the latest version of Android?

Thank you.
KM6HVW

**Comment by ge0rg** [comment]
This has been a major issue with Android 10 indeed. I've provided a new build on Google Play Beta and a new APK on the webserver, please see https://github.com/ge0rg/aprsdroid/issues/233#issuecomment-575652508 for details.
