### ISSUE TITLE
No Path Format Bug

### ISSUE THREAD

**Issue by na7q** [ge0rg/aprsdroid#273]
So it appears that the APRS servers are rejecting APRSDroid packets that have no path. I think this is both a problem with the APRS servers, and with APRSDroid in all versions. 

NA7Q-7>APDR15,:=4610.25N/12334.25W>
The comma presented after the tocall is the issue. With it, the APRS servers will completely reject the packet from the network. Even though it's still valid and all software and radios I've tried have displayed the packet correctly. APRS servers never used to reject it from what I recall, but it seems they are now.

**Comment by ge0rg** [comment]
This should be fixed in the latest test APK: https://aprsdroid.org/download/builds/aprsdroid-gl-2020-08-24.apk

**Comment by ge0rg** [comment]
I've now published APRSdroid 1.6 to Google Play ([direct APK download](https://aprsdroid.org/download/builds/aprsdroid-gl-2020-08-28.apk)). It contains the fix.
