### ISSUE TITLE
feature request: start tracking automatically upon start

### ISSUE THREAD

**Issue by iddq** [ge0rg/aprsdroid#276]
feature request: start tracking automatically upon start
(remember last state of tracking)

**Comment by ge0rg** [comment]
APRSdroid will normally remember the last tracking state, and resume tracking after you restart your android device. In theory, if you are tracking, Android will restart APRSdroid if it was killed (e.g. due to out-of-memory), so this should work in all conditions.

**Comment by iddq** [comment]
it does not work for me with 1.6.0
