### ISSUE TITLE
1.6 is crashing without Google Play services installed

### ISSUE THREAD

**Issue by jakern** [ge0rg/aprsdroid#278]

**Comment by ge0rg** [comment]
I was fearing this would happen with the new version. Can you provide a stacktrace? Otherwise I'll try to find a device with no Play Services and see where it goes down in the next days.

**Comment by jakern** [comment]
Here are the errors.

[logcat_08-29-2020_15-13-00.txt](https://github.com/ge0rg/aprsdroid/files/5145891/logcat_08-29-2020_15-13-00.txt)

**Comment by ge0rg** [comment]
Thanks very much! I should have fixed all of them except for the `FileUriExposedException` in today's build.

APK: https://aprsdroid.org/download/builds/aprsdroid-gl-2020-08-29.apk

It should appear in the next minutes on Google Play beta and some hours later on the proper Google Play, but I suppose that doesn't matter much if you don't have Google Play Services ;)

**Comment by jakern** [comment]
Fantastic! I still don't see the OSM map but that could be something else. Now that the crashing stopped I can troubleshoot. Thanks a bunch!
