### ISSUE TITLE
message sending to own callsign but other SSID will appear as received message

### ISSUE THREAD

**Issue by iddq** [ge0rg/aprsdroid#283]
if you send a message to your own callsign (to other SSID) you will get the message and notification like the message received from the network even if it is not a received message, this is the message that you send.

reproduce:
connect to the APRS-IS network with owncallsign-10
send a message to owncallsign-1
you will receive a message and notification from owncallsign-10

v1.6.0

**Comment by ge0rg** [comment]
I've added a check to ignore messages from your own callsign+ssid combo in 5294ed6bc8c036c1eb6ebefc1466616995f7f196.

Please test this APK: https://aprsdroid.org/download/builds/aprsdroid-gl-2020-10-01.apk

**Comment by iddq** [comment]
And how could it appear as a received message if it was not received from the network?

**Comment by ge0rg** [comment]
APRSdroid processes all packets in exactly the same way, no matter where they come from. This has many benefits, and sometimes some small drawbacks ;)
