### ISSUE TITLE
Feature request: codec2 voice communication support

### ISSUE THREAD

**Issue by sh123** [ge0rg/aprsdroid#287]
Probably it is outside of this application scope, but Is it possible to implement voice codec2 support in APRSDroid? 

So in addition to sending and receiving APRS data over Bluetooth it will also be able (configurable or on dedicated button hold) send/receive codec2 encoded speech from the mic, decode received data and play it to the speaker?

**Comment by ge0rg** [comment]
This is really far out of the app's scope indeed. You are probably looking for a walkie-talkie style app that'd do Codec2 over AFSK(?). AFSK is a really low-bitrate and basic modulation, and I'm sure there are better ones available.

**Comment by sh123** [comment]
Not necessary AFSK, it could run two streams over 9600 GMSK or any other modem, which could be interfaced over bluetooth.

**Comment by dranch** [comment]
Just a comment here but APRS has nothing to do with voice communications.  If you're looking for CODEC2 voice communications, there are other non-patented digital voice projects out there such as https://m17project.org/ , https://perens.com/2019/05/23/ht-of-the-future-new-design/ , and several others.  If you don't care about patented, there is Dstar, DMR, YSF, NXDN, etc.  Anyway... none of this is relevant to this excellent, purpose built APRS client for Android.  Thanks ge0rg for this great program!

**Comment by sh123** [comment]
I see, thanks for feedback, closing this request.

**Comment by sh123** [comment]
Just quickly built separate Android application, which does that https://github.com/sh123/codec2_talkie
