### ISSUE TITLE
Samsung Note 4 no menu access

### ISSUE THREAD

**Issue by samcrimm** [ge0rg/aprsdroid#288]
Hi, 
I have an old note 4 SM-N900V attached are pictures of the phone information.
I am wanting to use this with my HT to do APRS with out the internet connection.  But I have downloaded twice and have gone from portrait to landscape and I still don't see the menu 3 dots.  I have swiped and tried it all I can think of.   Attached are pictures of the screen for you to review.
![_MG_6845](https://user-images.githubusercontent.com/73452147/100249523-43de1500-2f02-11eb-829f-616b75f8aa56.JPG)
![_MG_6846](https://user-images.githubusercontent.com/73452147/100249547-4a6c8c80-2f02-11eb-9d6f-4637dd8fba7d.JPG)
![_MG_6847](https://user-images.githubusercontent.com/73452147/100249563-4f314080-2f02-11eb-92e2-42396578775b.JPG)
![_MG_6848](https://user-images.githubusercontent.com/73452147/100249571-52c4c780-2f02-11eb-9197-40ba60e282d9.JPG)

 Thanks for you help.  Sam

**Comment by penguin359** [comment]
This should only happen if the device reports it has a hardware menu key. Try holding the Task key at the bottom of the phone for one second and see if that brings up the missing menu items.

**Comment by penguin359** [comment]
https://allaboutgalaxynote.com/galaxy-note-4-how-to-guides/how-to-access-galaxy-note-4-hardware-menu-button/#Is-hardware-menu-button-obsolete
