### ISSUE TITLE
Connection refused with "Weak certificate" when using LotW certificate

### ISSUE THREAD

**Issue by gunnarre** [ge0rg/aprsdroid#296]
When connecting to ssl.aprs2.net I get the error message
`# Client certificate not accepted: EE certificate key too weak`
This is with a recently issued LotW certificate, but I wonder if it's the application's certificate that is the issue?

**Comment by gunnarre** [comment]
Working:

- northwest.aprs2.net

Not working:

- ssl.aprs2.net
- rotate.aprs2.net
- sweden.aprs2.net

**Comment by debugrr** [comment]
I believe this was the same issue as Issue #238. 

Expired certs + certs given with expired intermediate.
