### ISSUE TITLE
Object Icons not displaying correctly 

### ISSUE THREAD

**Issue by braddorl** [ge0rg/aprsdroid#297]
I updated an older tablet (Tab3) to the 3-2-2021 APK because of an unrelated factory reset. Now the station icons do not display on map; text is readable. Same build works fine on Galaxy S10.

Thanks for a great application.

Randy 
N1VTT

**Comment by braddorl** [comment]
I updated my tablet to a Samsung Galaxy TabS7 and the Object icons are clipped regardless of zoom level. 
![16161949126752419926580078669374](https://user-images.githubusercontent.com/11592389/111850121-c2155b80-88e5-11eb-85f4-150ad6fa32b7.jpg)

**Comment by ge0rg** [comment]
This is a bug with rendering the icons on Google Maps on older devices. I've published a new release on [the Play beta channel](https://play.google.com/apps/testing/org.aprsdroid.app) and as [APK](https://aprsdroid.org/download/builds/aprsdroid-gl-2021-06-08.apk). Please report if there are any remaining issues.
