### ISSUE TITLE
Feature Request: KISS-over-TCP

### ISSUE THREAD

**Issue by mattbk** [ge0rg/aprsdroid#300]
First off, thanks for this wonderful software. I'm learning so much about APRS and how it can be used, which wouldn't have been possible without this app.

This is semi-related to https://github.com/ge0rg/aprsdroid/issues/295, but it would be nice to connect to the TNC from another network using IP address or domain name. Rather than using autodiscovery on the network, the user would enter host (IP or domain) and port number.

Example use case: running direwolf as a digipeater or iGate and wanting to monitor local RF traffic while away from the network.

**Comment by ge0rg** [comment]
That's already possible, just set the connection protocol to "TNC (KISS)" and then the connection type to "TCP/IP". You can enter a host:port then.

**Comment by mattbk** [comment]
Thank you so much!
