### ISSUE TITLE
When moving to APRS.FI, the frequency is entered together.

### ISSUE THREAD

**Issue by otstn1010** [ge0rg/aprsdroid#302]
![aprsfi](https://user-images.githubusercontent.com/56328009/120090044-78918a00-c13a-11eb-8f2d-c71080467066.jpg)
First of all, the language is Korean, and in APRSdriod, select the call sign and APRS.Click View in fi to view APRS.When moved to fi, the frequency is also entered in the search window, so it is not searched.
(For example, if HL0HQ-1 Station is set to 144.500 MHz, APRS).It should be searched as "HL0HQ-1" in the fi search window, but it is entered as "HL0HQ-1 144.500" and no search results are available)

**Comment by ge0rg** [comment]
Thank you for the report. This also seems to affect sending messages to other operators, so something went wrong in the callsign extractor. I'm investigating this issue and will provide an update to the app soon.

**Comment by ge0rg** [comment]
This is a bug with opening station links from the Google Map view. I've published a new release on [the Play beta channel](https://play.google.com/apps/testing/org.aprsdroid.app) and as [APK](https://aprsdroid.org/download/builds/aprsdroid-gl-2021-06-08.apk). Please report if there are any remaining issues.
