### ISSUE TITLE
callsign message list bug -> v1.6.0e

### ISSUE THREAD

**Issue by GarminWFN** [ge0rg/aprsdroid#305]
hi,

I am on the version 1.6.0e with a Google Pixel 5 (Android 11).

there seems to be a bug with the display of the list of stations in the message section

the list of messages by callsign doesn't update when a new message is received, it only displays the first message of a conversation.

screenshots:

****The callsign message list doesn't update ... the list displays only the first message of a conversation**** 
![aprs1](https://user-images.githubusercontent.com/88301844/127804325-cae51636-16df-4629-b746-dd09c5048c52.png)

 several other messages since the first message...
![aprs2](https://user-images.githubusercontent.com/88301844/127804328-abec166b-4489-4cee-8ec0-34cefee7217b.png)

73'
Yannick VE2WFN

**Comment by debugrr** [comment]
It's Updating correctly for my Samsung Galaxy Note 9 with Android 10. 

Do you mind attaching your notification settings? (In the app)
Also, Does do you have that same issue if you clear those messages, and then resend.

**Comment by GarminWFN** [comment]
Yes , I have the same problem after delete messages or completely deleting the app cache

![Screenshot_20210803-212507](https://user-images.githubusercontent.com/88301844/128108423-3e1294c1-c9f8-44fb-84a4-94d5cde0abb0.png)

**Comment by debugrr** [comment]
Thanks, couple more quesitons. 
are you running IS or TNC, or AFSK? 

And do you mind sending the connection log?

**Comment by debugrr** [comment]
Researching, but it may be an issue with the way Android 11 handles Message intents. 

Not sure how to fix.

**Comment by ge0rg** [comment]
Thanks for the report. This is actually a logic bug in APRSdroid about collecting the messages from history. I'll check how to fix it in the next days.

The code fetches all messages, does a `GROUP BY callsign` and then orders by the unique ID, which is greater for newer messages: https://github.com/ge0rg/aprsdroid/blob/master/src/StorageDatabase.scala#L448-L451

What's missing is to sort the original list by timestamp or ID, which apparently did happen in older versions of Android, but isn't guaranteed by SQL.

**Comment by ge0rg** [comment]
I have a fixed APK uploaded here: https://aprsdroid.org/download/builds/aprsdroid-gl-2021-08-31.apk - this will become part of the next 1.6.1 minor release.

**Comment by GarminWFN** [comment]
Thank you, it works well
