### ISSUE TITLE
frequent crashes on Pixel 4a, Android 11

### ISSUE THREAD

**Issue by shimniok** [ge0rg/aprsdroid#307]
Experiencing frequent crashes of app and service on Pixel 4a, Android 11, build RQ3A.210805.001.A1

Have tried APRS-IS and serial to Yaesu FTM-400 using Yaesu serial cable.

Happy to help troubleshoot, provide info, whatever you need.

**Comment by shimniok** [comment]
Experiencing frequent crashes of app and service on Pixel 4a, Android 11, build RQ3A.210805.001.A1

Have tried APRS-IS and serial to Yaesu FTM-400 using Yaesu serial cable.

Happy to help troubleshoot, provide info, whatever you need.

**Comment by shimniok** [comment]
Switched from Google sat/map to offline and no immediate crashes yet. Am sorting an issue with offline map not displaying correctly, however (probably my fault).

**Comment by ge0rg** [comment]
There was a number of crashes in the last release of the app. I've now pushed out APRSdroid 1.6.1 into Google Play and onto the website, so could you please try again with the updated version?

Are you using the app from Google Play or a manually installed one?

**Comment by shimniok** [comment]
Thanks, much appreciated. I'm using the Play version. I will let you know how the latest works.

**Comment by shimniok** [comment]
Looks like the crashes are solved. I tried running it for 10-20 minutes
with local and Google maps, using a couple sources (APRS-IS and I think I
did serial) and no crashes so looks like this is fixed.
