### ISSUE TITLE
Latitude and longitude shown incorrectly when manually choosing location on map

### ISSUE THREAD

**Issue by LieBtrau** [ge0rg/aprsdroid#314]
Using Aprsdroid v1.6.2
Preferences -> Position Reports -> Location Settings -> Location Source=manual Position / Manual position -> Choose on Map

Latitude problem:
-----------------------
Locations on the southern hemisphere as shown as negative numbers with suffix 'S'.  Either use negative numbers with suffix 'N', or preferably use positive numbers with suffix 'S'.
e.g. Cape Town is shown as -34°S.

Longitude problem:
--------------------------
For locations in the eastern hemisphere, the longitude is shown as a positive number with suffix 'W'.
e.g. Location of Hong Kong is currently shown as 22°...N 114°...W.

either the longitude should be shown as -114°..W or preferably shown as 144°...E

**Comment by penguin359** [comment]
I have confirmed this bug on the latest release. There are two difference issues at play here. One is that latitude/longitude sometimes show as negative which it never should when using explicit cardinal directions. Second, East and West appear to be flipped on the longitude.

I will work on a fix for this and get it pulled in.

**Comment by ge0rg** [comment]
Damn, how could I have missed this obvious oversight? Thanks for the report, and many thanks to @penguin359 for the fix!

I've uploaded 1.6.2b to Google and Amazon, and [there is an APK](https://aprsdroid.org/download/builds/aprsdroid-gl-2022-01-05.apk).
