### ISSUE TITLE
TCP connection going to port 24580, APRS service stops immediately

### ISSUE THREAD

**Issue by CraigBos** [ge0rg/aprsdroid#340]
All of the sudden I can't Start Tracking.  Looking at APRSdroid Log, it seems to be attempting to connect with Port 24580 instead of port 14580.  I never looked at this before, so I don't know if this is normal.  Please advise how to correct, or what additional information would be helpful.

Thank you.

![Screenshot_20230129-211811-edit](https://user-images.githubusercontent.com/106816785/215375120-c8674aa1-206f-4c52-8283-7bebf5e83067.png)

**Comment by CraigBos** [comment]
Turns out I needed to configure the server to ssl.aprs2.net.  Not sure how I lost that.  It's working as before now.

**Comment by ge0rg** [comment]
Port 24580 is the SSL port, 14580 is the standard port. APRSdroid will automatically use 24580 if there is a certificate in the app.

**Comment by CraigBos** [comment]
> Port 24580 is the SSL port, 14580 is the standard port. APRSdroid will automatically use 24580 if there is a certificate in the app.

That explains it.  Thank you.
