### ISSUE TITLE
Am I able to send a message to a Callsign with position data?

### ISSUE THREAD

**Issue by troilus** [ge0rg/aprsdroid#349]
Or change the destination of Send Location form APRxxx to a specific destination.

**Comment by penguin359** [comment]
The destination field is not used for controlling where the message goes, in general. It's specified to either contain a generic APRS address or a software version like APRxxx in that field only. Only the source field contains a regular callsign of the amateur sending the message. APRS messages actually include an additional field to include the destination of that message and this field is not present in location beacons. In general, APRS is a broadcast network with a special case of directed text messaging that receivers can filter on.

There is a possibility of just including latitude/longitude encoded as plain-text in a message, but it would not be nearly as compact as the encoding used for location beacons or recognized automatically by receiving software.
