### ISSUE TITLE
Crash from USB connection attempt on pixel 5

### ISSUE THREAD

**Issue by Prep5242** [ge0rg/aprsdroid#364]
I'm trying to get APRSdroid working with my nucleoTNC, and I've done so in the past with a different phone, but I'm currently using a pixel 5 running android 14. 

The app crashes immediately upon attempting to 'start tracking' or 'send position,' only when connection is set to USB and the TNC is connected; APRS-IS works fine and if it's not plugged in I get 'No USB device found' with no crash. The log will read 'APRS service started' then 'Found USB device,' then nothing else until I reopen the app, attempt again, and get those same 2 entries.
![Screenshot_20240209-205048](https://github.com/ge0rg/aprsdroid/assets/49247285/87d6d860-f50c-4ecc-a600-426d9e62a867)
^these simply repeat once in the log with every attempt.

I've tried changing the map settings to an offline map file, double checking APRSdroid permissions in settings, and my connection preferences are set to TNC (KISS), USB serial, and 38400 baud. If there's some way to get a crash report I'd be happy to try that too.

**Comment by ge0rg** [comment]
Thanks for the report, it was a change in the permission setup that backfired. Should be fixed now in 1.6.3d on Google Play ([apk](https://aprsdroid.org/download/APRSdroid-1.6.3d.apk)).
