### ISSUE TITLE
The third method

### ISSUE THREAD

**Issue by bg1fpx** [ge0rg/aprsdroid#374]
If I want ARPSdroid to send my positions continuously and automatically, I can use two methods: (1) keep screen on, or (2) an automation app, such as Tasker. My issue is: do I have the third method?

**Comment by penguin359** [comment]
Have you disabled the setting "Pause app activity if unused" under Permissions? This might help, but I have seen this behavior on a completely different app, AllTrails, which sometimes stops recording my position until I open the app again.
