### ISSUE TITLE
Feature Request: Option to allow duplicates.

### ISSUE THREAD

**Issue by TheCommsChannel** [ge0rg/aprsdroid#380]
I'm working on a BBS-like system for APRS which is menu driven. Being that its menu driven, the problem I run into is the end user will sometimes receive packets with the same messages and APRSdroid won't display them. If I clear the message session and try again, the messages come through fine until they get sent again, so it seems as if APRSdroid is not displaying duplicate messages in the same message session.

It would be great if there was an option to allow duplicates for use-cases like mine.

**Comment by richonguzman** [comment]
do you mean the packet APRSDROID receives over a certain time? (like 30 secs time delta?)?

**Comment by TheCommsChannel** [comment]
Correct. I'm not sure what the time delta is if there is one, but even after getting the same packet 10 minutes later, it still won't show unless I clear the chat.

**Comment by na7q** [comment]
Are you using message IDs? I'm a bit curious of your usage.
Show me a couple examples of the raw packets?

**Comment by na7q** [comment]
> Correct. I'm not sure what the time delta is if there is one, but even after getting the same packet 10 minutes later, it still won't show unless I clear the chat.

I'm assuming it's not that important, or you figured out your issue?

**Comment by TheCommsChannel** [comment]
Same issue. Just not had time to work on the project but will be working on it again soon.

**Comment by na7q** [comment]
> Same issue. Just not had time to work on the project but will be working on it again soon.

Since I've started working on improving and adding minor things lately, trying to better understand the code and overall design. I'll see what I can find with this. If I'm lucky I can add a setting and time limit perhaps to it.

**Comment by na7q** [comment]
> Same issue. Just not had time to work on the project but will be working on it again soon.

I've started the implementation of this. It may takes me a short while, but initial tests prove successful. Since I'm attempting to add support for bulletins, this naturally becomes a necessary feature to have. As soon as I come up with the best solution for the bulletins, I can properly implement a setting on duplicate messages.

**Comment by TheCommsChannel** [comment]
> > Same issue. Just not had time to work on the project but will be working on it again soon.
> 
> I've started the implementation of this. It may takes me a short while, but initial tests prove successful. Since I'm attempting to add support for bulletins, this naturally becomes a necessary feature to have. As soon as I come up with the best solution for the bulletins, I can properly implement a setting on duplicate messages.

Sweet! Good to hear the initial tests have been successful. I'll have more time this month to work on the BBS this month, so this is greatly appreciated!

**Comment by TheCommsChannel** [comment]
Perfect! Just needed the ability for duplicates as the bulletins will be on the server side so this works. I'll give it a go!

**Comment by na7q** [comment]
Let me know if you run into any issues or need something else done. I have a couple of weeks off of work coming, so I'll be able to tackle some other things soon.

**Comment by TheCommsChannel** [comment]
Thanks again for this! Initial tests are successful so I should be good to go, but I'll let you know if I hit any snags as I continue working on this. Also, got it working with the Set Frequency option 😎

I'll go ahead and close this since it's working.

**Comment by na7q** [comment]
Perfect! Will be seeing you on YouTube! Thanks for hanging in there. And just an FYI, I have a big release today with IGate functionality. I think I finally ironed it all out. If you want to give it a try, here it is.

https://na7q.com/wp-content/uploads/2024/12/aprsdroid-release-noapi-igate.apk
