### ISSUE TITLE
Blackberry Playbook - APK - Bar conversion failure

### ISSUE THREAD

**Issue by prdufresne** [ge0rg/aprsdroid#48]
I attempted to convert the APK for APRSdroid (Offline map version) to a BAR file for loading onto a Blackberry Playbook, however the conversion tool returns a compatibility error:

"Your application uses a feature which is incompatible with the current version of the BlackBerry® Runtime for Android™ Apps. We recommend that you download the BlackBerry® Plug-in for ADT to test your application and remove features as required."

The two runtime libraries it referenced were:
(AndroidManifest.xml) uses-feature: android.hardware.bluetooth
(AndroidManifest.xml) uses-library: android.test.runner

The Blackberry Playbook has a built-in GPS receiver, so it is an idea tablet for use with APRS if I can get the app to load.

Any chance I can get a version of the ADK that isn't reliant on these two libraries?

**Comment by ge0rg** [comment]
Is this still an open problem, or did you move on to a "real" Android or more recent BlackBerry device? :)

**Comment by prdufresne** [comment]
I'm no longer using the BB Z10, however, the most recent version of the OS for the device allowed it to load APRSdroid. This is no longer needed.
