### ISSUE TITLE
Configuring APRS symbol not working

### ISSUE THREAD

**Issue by PeterSprague** [ge0rg/aprsdroid#59]
No matter which symbol designation I choose, my symbol stays as /$ , aka a phone.  Only way I got the symbol to change was to delete all data, and start afresh with install.

It now shows /< on map.

Thanks for this software.  Use it in the bush here in British Columbia.  If anything would happen, helps search and rescue and puts my wife more at ease.

Peter

**Comment by ge0rg** [comment]
Now this has been pending for faaaaar to long.
New apk with symbol picker: http://aprsdroid.org/download/builds/APRSdroid-gl-2016-09-21.apk

Result:
![aprsdroid-symbol](https://cloud.githubusercontent.com/assets/165635/18703654/21079fe8-7fe7-11e6-9272-8f24e73d0b90.png)

Please test and report back!

**Comment by KU7PDX** [comment]
I've just downloaded the latest non-OSM build and noticed after picking the symbol, I can't enter anything into the "Overlay:" field. Otherwise, this feature looks great! Thank you for continuing to improve APRSdroid!

**Comment by ge0rg** [comment]
Not all symbols can be overlaid. This is reflected in the 'Overlay' text box. Try to use a symbol with a blank space inside, these should work generally.

More details: http://www.aprs.org/symbols.html

**Comment by KU7PDX** [comment]
Ah, thank you! I clicked around some more and found a few that allowed me to enter a character in the Overlay text box.

What I was originally trying to do is select the "Runner" icon and apply a "H" overlay on it to reflect "Hiker" per the 2007 APRS symbol expansion, but I now realize that isn't supported yet.
