### ISSUE TITLE
No TX or RX data on TNCX bluetooth

### ISSUE THREAD

**Issue by megagertz** [ge0rg/aprsdroid#63]
I am able to pair my phone and tabled running APRSDroid V 1.2.2.  The TNCX Bluetooth LED turns on solid however I do not see any data from the TNC and cannot transmit messages or position.  I have tried using my phone and my tablet and get the same results.  

I did run S2 terminal for Bluetooth on my phone and can receive data from the TNC.  It is unreadable but there is data coming in.

do you have any ideas on how to correct this issue?

Thank you

**Comment by ge0rg** [comment]
Any news?
