### ISSUE TITLE
messages to calls that are written with small  letters will not be ackowledged

### ISSUE THREAD

**Issue by zem** [ge0rg/aprsdroid#81]
I don't know if you are aware of that, it is mainly a problem with the igates. 

You may send: 

OE1SRC-1>WIDE-2::dd5tt    :test{3

It will arrive unharmed but even if dd5tt sends back: 

dd5tt>APQTC1,WIDE-2::OE1SRC-1 :ack3

aprsdroid will receive: 

DD5TT>APQTC1,WIDE-2::OE1SRC-1 :ack3

which is not going to be acked. 

my Idea would be to make it impossible to type in lower case calls. maybe a setting, so you can switch it off if needed. This would it make a lot easier to type in calls anyway. 

regards 
     Hans

**Comment by ge0rg** [comment]
I have further restricted the input field for callsigns in 2ff245a7b6391ea81bbcfa4ada47117fe02ed4e4.

This will be published as 1.4 soon.
