### ISSUE TITLE
Feature Request:  APRS Object Beaconing

### ISSUE THREAD

**Issue by ptc2y** [ge0rg/aprsdroid#83]
Is there a way to beacon object positions manually?  One can beacon their callsign-SSID manually, however, beaconing tactical object positions and your physical position (via periodic or smart beaconing) when providing public safety assistance would be very helpful.

**Comment by ge0rg** [comment]
I'm working on an API to allow additional apps to create/maintain objects and other APRS data. Stay tuned for the 1.3.0 release, due in the next days/weeks.
