### ISSUE TITLE
feature request: add support for mapsforge xml render-theme (OSM version)

### ISSUE THREAD

**Issue by theksmith** [ge0rg/aprsdroid#86]
first of all thanks for the great app, i'm just getting into APRS and i'm glad there is something nice out there for Android-based systems.

the problem i have is that topo OSM maps do not display in a very usable manner. i'm sourcing maps from here: http://www.openandromaps.org/en/

the root issue is that APRSdroid doesn't seem to allow xml based render-themes and the built-in theme ignores a lot of the info within the .map file. i believe you're using the open mapsforge project for OSM display so hopefully it is somewhat simple to just a check for a specific path/file and make use of it if present. a file chooser would be optimal but is not necessary if it would slow down getting the feature out.

here's what the US AZ-NM map looks like in APRSdroid: https://lh4.googleusercontent.com/-XV8QmIK7S5g/VBRY_SY27lI/AAAAAAAAFQ4/Dh-WvGZb5Sw/s800/Screenshot_2014-09-12-11-50-15.png

here is the same .map file in Locus Map Pro with one of their default themes applied: https://lh4.googleusercontent.com/-cPfKsbgXUQc/VBRZAX_-X3I/AAAAAAAAFRE/Ty7JaKw9SHg/s800/Screenshot_2014-09-12-11-51-34.png

and here is the same exact map again but in OruxMaps using one of the themes available on OpenAndroMaps: https://lh5.googleusercontent.com/-w5uuUdCzxg4/VBRZBBOcbcI/AAAAAAAAFRI/jxYW0RlNaOA/s800/Screenshot_2014-09-12-11-50-08.png

i've tried the latest build (APRSdroid-gl-2014-09-09_osm.apk) and an older one (APRSdroid-gl-2013-08-19_osm030.apk) - the maps i have seems to render the same so i don't think this is a duplicate of issue #85.

thanks!

**Comment by braddorl** [comment]
I am unable to get this working on either the root or an sdcard. I get an error along the lines of error loading null map file! But the aprsdroidmap works, even though i get an error when i try to select it from in aprsdroid.

randy

**Comment by ge0rg** [comment]
This has been resolved in #101
