### ISSUE TITLE
AFSK via Speaker/mic only works with Single Shot

### ISSUE THREAD

**Issue by confuzzledham** [ge0rg/aprsdroid#88]
I'm using a Galaxy Centura with a Baofeng UV-82. I'm using VOX to trigger the radio's PTT. For some reason if I use the "Single Shot" mode the radio transmits the packet like it should but if I hit "Start Tracking" no packets are transmitted even though the phone has a GPS fix. Further, on the rare occasion I do get Tracking to work my local digipeter will not decode the traffic and nothing shows up on APRS.fi. However, if I hit "Stop Tracking" and then hit "Single Shot" the packet goes through fine and my location shows up right away on APRS.fi. 

I listened to the packets with a pair of headphones and they sounded the same either way. What's going on here?

**Comment by ge0rg** [comment]
Any news from your cable tests?
