### ISSUE TITLE
APRSdroid's position comment starts with whitespace, confuses D7x0

### ISSUE THREAD

**Issue by kernelworks** [ge0rg/aprsdroid#93]
I noticed a small incompatibility between Aprsdroid and the Kenwood D710's so-called "Automatic Frequency Reporting System".

_Configuration_
  - Radio 1
    - Aprsdroid, mobilink TNC, mobile VHF transceiver
    - Aprsdroid version: 1.2.3-17-g10b4282 2013-08-19
  - Radio 2
    - D710GA

When Aprsdroid receives an APRS packet containing a comment with the first 10 chars "FFF.FFFMHz" it interprets it as a frequency and displays it in large bold digits. This works great when the D710 has this feature enabled as it automatically inserts the B-band voice frequency in the comment and Aprsdroid displays it.

Something odd happens in the other direction: aprsdroid => D710. When Aprsdroid comment is set to 10 chars "FFF.FFFMHz", it prepends the comment with a space before it's transmitted. The first 10 chars of comment field of the packet is thus " FFF.FFFMH". The D710 is perhaps very picky as it won't display the frequency, and the operator cannot press [TUNE] to automatically set it in the B-band VFO. 

I looked at the raw packet data in the aprsdroid log and D710, as well as on aprs.fi. I didn't capture logs, or a sample raw APRS packet to show here, but I can certainly do that if needed.

I didn't see a similar ticket opened; if there is please feel free to mark this as a duplicate, close or disregard. Hopefully it's useful.

**Comment by ge0rg** [comment]
Okay, this has been harder than anticipated. APRS frequency must be placed at the beginning of the comment, unless there is a speed/course field which precedes frequency. Altitude however must be placed after the frequency.

I've solved the problem by adding a frequency input box into the app:

![frequency](https://cloud.githubusercontent.com/assets/165635/19147763/ea39e4f6-8bb9-11e6-92ae-457e238180a1.png)

APK Download: http://aprsdroid.org/download/builds/APRSdroid-gl-2016-10-06.apk
