### ISSUE TITLE
Selectable metric or imperial units.

### ISSUE THREAD

**Issue by uspshooter** [ge0rg/aprsdroid#98]
Much-needed ability to configure metric or imperial units of measure within the settings menu. Otherwise this is a great app!
73 DE N0XVB

**Comment by ge0rg** [comment]
I am really sorry, but as the application is developed in Europe, I am bound by the [EU Directive 80/181/EEC](http://en.wikipedia.org/wiki/European_units_of_measurement_directives#Directive_80.2F181.2FEEC) which requires the use of the International System of Units (SI) and does not allow alternative unit systems like the Imperial Estimates.
