### ISSUE TITLE
RMarkG

### ISSUE THREAD

**Issue by RMarkG** [ge0rg/aprsdroid#99]
I have used aprsdroid with a Droid RazorM.  I recently changed to an LG G3.  I cannot locate a way to get to the menu settings.  Am I missing something or does it not show on the LG.  Thanks

73

K3VL    k3vl@comcast.net

**Comment by ge0rg** [comment]
Long-press the "multi-task" button. This will be fixed real-soon-now[tm] when APRSdroid 1.3.0 goes live.
